### ISSUE TITLE
欢太网页版抓取的cookie没有source_type这一项，

### ISSUE THREAD

**Issue by qianmugg** [Mashiro2000/HeyTapTask#10]
在抓取的cookie类似于
执行时说缺少source_type字段
请问这种情况是抓取方法有问题还是服务器现在发出的cookie格式改变了呢？

**Comment by Mashiro2000** [comment]
欢太好像只支持手机，因为需要用到设备信息，否则不能执行一些脚本，推荐手机抓包

**Comment by Mashiro2000** [comment]
修改了你的问题内容，ck不要随便暴露给其他人

**Comment by wfinewy** [comment]
用手机抓
