### ISSUE TITLE
sendnotify.py文件内容一直错误

### ISSUE THREAD

**Issue by whyman365** [Mashiro2000/HeyTapTask#101]
![微信图片_20211110095923](https://user-images.githubusercontent.com/85566456/141035699-4ffd54a6-4710-4cfd-ae8d-56112d57f32d.png)
sendnotify.py文件从6日开始就被篡改为html文件，不知道是那个脚本干的

**Comment by a54731037** [comment]
同

**Comment by Mashiro2000** [comment]
重新拉取吧

**Comment by Oreomeow** [comment]
估计是你的网络环境不好，建议你把拉库命令 sendNotify 参数去掉，手动下载

**Comment by Oreomeow** [comment]
> 重新拉取吧

你用 tg 吗，加个群呗
