### ISSUE TITLE
每天说token 失效了 登录失败

### ISSUE THREAD

**Issue by 986244073** [Mashiro2000/HeyTapTask#103]
每天说token 失效了 登录失败

**Comment by Mashiro2000** [comment]
请检查ck是否完全

**Comment by 986244073** [comment]
ck可以放在qinglong环境里面吗

**Comment by Mashiro2000** [comment]
一开始是使用环境变量，但是青龙会破坏掉j`son`字符串，所以改用配置文件

**Comment by Oreomeow** [comment]
> 一开始是使用环境变量，但是青龙会破坏掉 `json` 字符串，所以改用配置文件

主要是 `/ql/config/env.sh` 里面声明的变量，有联系方式不？

**Comment by Mashiro2000** [comment]
> > 一开始是使用环境变量，但是青龙会破坏掉 `json` 字符串，所以改用配置文件
> 
> 主要是 `/ql/config/env.sh` 里面声明的变量，有联系方式不？我之前遇到类似情况采用回车即可实现

463022229
