### ISSUE TITLE
这里多个了flag=1

### ISSUE THREAD

**Issue by FgywAwut** [Mashiro2000/HeyTapTask#106]
https://github.com/Mashiro2000/HeyTapTask/blob/601c6fec536f89395614cf979389425be7c849f9/OnePlusJYStation.py#L232

**Comment by Mashiro2000** [comment]
> https://github.com/Mashiro2000/HeyTapTask/blob/601c6fec536f89395614cf979389425be7c849f9/OnePlusJYStation.py#L232

这个无所谓，之前遗留的，看看后续是否还需要使用到
