### ISSUE TITLE
大佬 这是什么情况啊？没雨报错，但是也没有执行结果，所有任务都是

### ISSUE THREAD

**Issue by 344108150** [Mashiro2000/HeyTapTask#108]
![image](https://user-images.githubusercontent.com/90685197/141395293-4d388f74-8ec8-4f2b-9a9d-9ffe70bd2425.png)

**Comment by benzBrake** [comment]
你没有添加账号

**Comment by 344108150** [comment]
我有账号啊 
![image](https://user-images.githubusercontent.com/90685197/141419148-b34fb9f0-6e27-4fcf-9118-c6c3d89b3eb8.png)

**Comment by 1335344215** [comment]
貌似是不兼容最新的版本
![image](https://user-images.githubusercontent.com/33363399/141426498-b5ae96b4-77a6-4dd9-884d-3d133a1eb782.png)

**Comment by 1335344215** [comment]
2.10.5

**Comment by benzBrake** [comment]
今天我更新青龙，也有这个报错了，回滚了，你等 repo 作者 @Mashiro2000 看看怎么回事

**Comment by okmqazqwerty** [comment]
确实好像抓取了ck也一样失效了，等大佬更新吧

**Comment by Mashiro2000** [comment]
> 确实好像抓取了ck也一样失效了，等大佬更新吧

CK无问题，可能是你刚好过期了

**Comment by Mashiro2000** [comment]
> 今天我更新青龙，也有这个报错了，回滚了，你等 repo 作者 @Mashiro2000 看看怎么回事

建议备份CK，重新拉取脚本，再次运行

**Comment by spark1001** [comment]
+1，我也出现这情况了，昨天用青龙2.10.5还是可以的，今天更新了一下2.10.6，就变成全空白了，账号是有的，但是啥也不执行

**Comment by 344108150** [comment]
更新新版本 所有问题都解决了

**Comment by benzBrake** [comment]
> 
> 
> 确实好像抓取了ck也一样失效了，等大佬更新吧

@Mashiro2000 今天新的Find X3到了，我加新号发现 isNewPeople 地址的 Cookie 里 没有 source_type 关键字了，不过随便找了一个图片地址（sa.gif）的Cooke里有。

**Comment by cisco6005** [comment]
+1我早就出现这个情况了，青龙2.10.0版本就出现了，目前还没解决，CK没有过期，配置正常，就是不报错也没有执行结果

**Comment by Mashiro2000** [comment]
> > 确实好像抓取了ck也一样失效了，等大佬更新吧
> 
> @Mashiro2000 今天新的Find X3到了，我加新号发现 isNewPeople 地址的 Cookie 里 没有 source_type 关键字了，不过随便找了一个图片地址（sa.gif）的Cooke里有。

好的，我留意一下

**Comment by Mashiro2000** [comment]
你重新拉取脚本，运行看看，我改了代码逻辑
