### ISSUE TITLE
青龙2.10.5无法拉取

### ISSUE THREAD

**Issue by kuilei0926** [Mashiro2000/HeyTapTask#109]
![image](https://user-images.githubusercontent.com/17094610/141433365-0cfc08ff-312f-4588-862a-01da13d36b0a.png)

**Comment by Mashiro2000** [comment]
好的，我回去看看

**Comment by 344108150** [comment]
复议

**Comment by timelast** [comment]
复议

**Comment by okmqazqwerty** [comment]
这个问题在2.10.3好像也有，一样的Validation error, cannot resolve alias

**Comment by Polaris-7** [comment]
作者老哥，今天所有欢太脚本都无法运行了，感觉是依赖问题，青龙更新了就不行了

**Comment by Mashiro2000** [comment]
> 作者老哥，今天所有欢太脚本都无法运行了，感觉是依赖问题，青龙更新了就不行了

可以运行的，如果不行的话，建议备份完CK，然后重新拉取

**Comment by Mashiro2000** [comment]
没有问题哦，可以先备份CK，然后删除脚本，重新拉取，最新版青龙规范了脚本仓库，需要再次填写CK信息

**Comment by Mashiro2000** [comment]
拉取失败的话，可以看看拉库命令是否正确

**Comment by Polaris-7** [comment]
> 没有问题哦，可以先备份CK，然后删除脚本，重新拉取，最新版青龙规范了脚本仓库，需要再次填写CK信息

好勒好勒

**Comment by 344108150** [comment]
应该是青龙面板的问题  更新 2.10.6 所有问题都解决了
