### ISSUE TITLE
请问是否有关闭通知的选项

### ISSUE THREAD

**Issue by uniqueww** [Mashiro2000/HeyTapTask#110]
请问是否有关闭通知的选项

**Comment by TurboJerry** [comment]
希望可以设置赚积分里面的天天抽奖为自动抽奖

**Comment by Mashiro2000** [comment]
> 希望可以设置赚积分里面的天天抽奖为自动抽奖

暂时未找到脚本抽奖失败的原因，故不设置抽奖

**Comment by Mashiro2000** [comment]
> 请问是否有关闭通知的选项

我得重构代码逻辑，，，

**Comment by Oreomeow** [comment]
@Mashiro2000 加在 HT_config 里面好了，我不想改配信文件了hhh

**Comment by Mashiro2000** [comment]
> @Mashiro2000 加在 HT_config 里面好了，我不想改配信文件了hhh 或者自己设个环境变量

已经有了，就是没有一个控制，全部关闭的选项
