### ISSUE TITLE
报错提示：authenticate token fail

### ISSUE THREAD

**Issue by kirito8** [Mashiro2000/HeyTapTask#111]
CK按顺序填的，运行任务报错
![874F291E-7DEF-45f6-94E3-605CFA7E8045](https://user-images.githubusercontent.com/22957293/141648693-dae22fce-302d-4087-9316-1355f3f0bcb4.png)

**Comment by benzBrake** [comment]
手机上你换号登陆了吧

**Comment by kirito8** [comment]
> 手机上你换号登陆了吧

没换号，重新抓了一次正常了
