### ISSUE TITLE
跑脚本出现 json数据不齐全

### ISSUE THREAD

**Issue by afwfv** [Mashiro2000/HeyTapTask#112]
登录成功
[每日签到]	已签到
[早起打卡]	您已经报过名了
****************************************

账号: 
状态: 取消登录
原因: json数据不齐全

**Comment by Mashiro2000** [comment]
user参数也配上

**Comment by Mashiro2000** [comment]
随便写，必要

**Comment by afwfv** [comment]
> 随便写，必要

我填了啊
![image](https://user-images.githubusercontent.com/62470022/141676288-6eb3401d-179b-46cf-9bc4-72f96ea0433f.png)

**Comment by Mashiro2000** [comment]
我去看看

**Comment by afwfv** [comment]
填完这个脚本会自动添加这个文件
![image](https://user-images.githubusercontent.com/62470022/141676321-ff28fda8-e132-45f9-8d14-ce5a7e11cf25.png)
不知道是否有关
我是直接去映射目录添加的，不去的话是图片这个样子
![W38JSX1W8@8)`7Y( JVLKW9](https://user-images.githubusercontent.com/62470022/141676389-5eb41017-cda1-457c-b8bb-eb1f8f89ac5c.png)

**Comment by afwfv** [comment]
![image](https://user-images.githubusercontent.com/62470022/141676414-d38d5ec3-6a42-49ce-94bc-122da31edbe5.png)

**Comment by Mashiro2000** [comment]
不要放映射文件里

**Comment by Mashiro2000** [comment]
第一次拉取
ql repo https://github.com/Mashiro2000/HeyTapTask.git "" "Backup|index|HT.*|sendNotify" "HT.*|sendNotify"

拉取完成后，修改拉库指令，确保HT_account.py不被覆盖，更改拉库命令，命令如下
ql repo https://github.com/Mashiro2000/HeyTapTask.git "" "Backup|index|HT.*|sendNotify" "HT_config|sendNotify"

**Comment by afwfv** [comment]
我是通过拉库，但是填完了会生成这个文件
![image](https://user-images.githubusercontent.com/62470022/141676548-fa41152b-5c9c-41bb-932f-d74554578bf0.png)
填ck那个文件没有ck，会跑到这个文件

**Comment by Mashiro2000** [comment]
我去检查下命令

**Comment by Mashiro2000** [comment]
好像没问题，

**Comment by afwfv** [comment]
> 好像没问题，

我重新部署青龙还是一样这个问题

**Comment by xinxuanjvshi** [comment]
我拉库更新完日志最后也出现
账号:
状态: 取消登录
原因: json数据不齐全
但是任务已经做好了
