### ISSUE TITLE
OPPO社区签到、早起打卡脚本出现问题

### ISSUE THREAD

**Issue by zmsnfly** [Mashiro2000/HeyTapTask#114]
> ## 开始执行... 2021-11-14 20:00:50
> 
> 
> 鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
> 该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
> 青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
> CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'
> 
> 任务:OPPO社区签到、早起打卡
> 时间:2021-11-14 20:00:50
>	登录成功
> [每日签到]	已签到
> Traceback (most recent call last):
>   File "Mashiro2000_HeyTapTask_Community.py", line 235, in <module>
>     main_handler(None,None)
>   File "Mashiro2000_HeyTapTask_Community.py", line 220, in main_handler
>     community.start()
>   File "Mashiro2000_HeyTapTask_Community.py", line 201, in start
>     self.earlyBed ()
>   File "Mashiro2000_HeyTapTask_Community.py", line 183, in earlyBed
>     self.SignUp()
>   File "Mashiro2000_HeyTapTask_Community.py", line 137, in SignUp
>     response = self.sess.post(url=url,headers=headers,data=data).json()
>   File "/usr/lib/python3.8/site-packages/requests/models.py", line 910, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> ## 执行结束... 2021-11-14 20:01:06 耗时 16 秒

**Comment by Mashiro2000** [comment]
可以给我你的CK，让我测试下吗，

**Comment by zmsnfly** [comment]
{
        'user':'zmsnfly',
        'CK':'source_type=501;TOKENSID=TOKEN_eyJhbGciOiJFQ0RTQSIsInYiOiIxIn0.eyJleHAiOjE2Mzg2MjgxOTU4MDMsImlkIjoiNjE0ODU3OTk4IiwiaWRjIjoic2hvdW1pbmciLCJ0aWQiOiIzcnQ0WmpGM0xCNzJUS1J1UTI3UlhYVHJJWjdxeWs0M0Ewa3dLTFUrUFpMTmJGUjE4QzVYaXlwOVBENGxqOGdKY2kvd0QrQVU5MWhCazh6UFJxa2JBekovYkJWRFFqUVU5UWsxRlRBd2grOD0ifQ.MEYCIQC8-CR-qZsxb_7BlZCIeLmamEoAFCvQv8zrT9VBBpeL1AIhAPGkICCm-rcz9BXqvZjdGWOFBEYI4VGGJjtmoF2vSp5S;app_param={"model":"vmos","brand":"Redmi","rom":"ROM","guid":"","ouid":"","duid":"","udid":"","apid":"","sa_device_id":"55576be86ce5ec36","romVersion":"V0.0","apkPkg":"com.oppo.store"}',
        'UA':'Mozilla/5.0 (Linux; Android 7.1.2; vmos Build/NZH54D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.117 Mobile Safari/537.36 oppostore/300004 ROM/V0.0 brand/Redmi model/vmos'
    }

**Comment by zmsnfly** [comment]
> 可以给我你的CK，让我测试下吗，

    {
        'user':'zmsnfly',
        'CK':'source_type=501;TOKENSID=TOKEN_eyJhbGciOiJFQ0RTQSIsInYiOiIxIn0.eyJleHAiOjE2Mzg2MjgxOTU4MDMsImlkIjoiNjE0ODU3OTk4IiwiaWRjIjoic2hvdW1pbmciLCJ0aWQiOiIzcnQ0WmpGM0xCNzJUS1J1UTI3UlhYVHJJWjdxeWs0M0Ewa3dLTFUrUFpMTmJGUjE4QzVYaXlwOVBENGxqOGdKY2kvd0QrQVU5MWhCazh6UFJxa2JBekovYkJWRFFqUVU5UWsxRlRBd2grOD0ifQ.MEYCIQC8-CR-qZsxb_7BlZCIeLmamEoAFCvQv8zrT9VBBpeL1AIhAPGkICCm-rcz9BXqvZjdGWOFBEYI4VGGJjtmoF2vSp5S;app_param={"model":"vmos","brand":"Redmi","rom":"ROM","guid":"","ouid":"","duid":"","udid":"","apid":"","sa_device_id":"55576be86ce5ec36","romVersion":"V0.0","apkPkg":"com.oppo.store"}',
        'UA':'Mozilla/5.0 (Linux; Android 7.1.2; vmos Build/NZH54D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.117 Mobile Safari/537.36 oppostore/300004 ROM/V0.0 brand/Redmi model/vmos'
    }

**Comment by Mashiro2000** [comment]
已收到

**Comment by Oreomeow** [comment]
哈哈哈我也一堆 JSON 错误

**Comment by Mashiro2000** [comment]
> 哈哈哈我也一堆 JSON 错误（别的签到脚本

OPPO社区默认是`application/x-protobuf`我`header`给他传了个`application/json`，能够运行，

**Comment by Mashiro2000** [comment]
> > ## 开始执行... 2021-11-14 20:00:50
> > 鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
> > 该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
> > 青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
> > CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'
> > 任务:OPPO社区签到、早起打卡
> > 时间:2021-11-14 20:00:50
> > 登录成功
> > [每日签到]	已签到
> > Traceback (most recent call last):
> > File "Mashiro2000_HeyTapTask_Community.py", line 235, in 
> > main_handler(None,None)
> > File "Mashiro2000_HeyTapTask_Community.py", line 220, in main_handler
> > community.start()
> > File "Mashiro2000_HeyTapTask_Community.py", line 201, in start
> > self.earlyBed ()
> > File "Mashiro2000_HeyTapTask_Community.py", line 183, in earlyBed
> > self.SignUp()
> > File "Mashiro2000_HeyTapTask_Community.py", line 137, in SignUp
> > response = self.sess.post(url=url,headers=headers,data=data).json()
> > File "/usr/lib/python3.8/site-packages/requests/models.py", line 910, in json
> > return complexjson.loads(self.text, **kwargs)
> > File "/usr/lib/python3.8/json/**init**.py", line 357, in loads
> > return _default_decoder.decode(s)
> > File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
> > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
> > raise JSONDecodeError("Expecting value", s, err.value) from None
> > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > ## 执行结束... 2021-11-14 20:01:06 耗时 16 秒

我这边测试没有问题，你再试试

**Comment by zmsnfly** [comment]
还是不行，测试了一下`response = self.sess.post(url=url,headers=headers,data=data)`返回的是Response [403]

> > > ## 开始执行... 2021-11-14 20:00:50
> > > 鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
> > > 该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
> > > 青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
> > > CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'
> > > 任务:OPPO社区签到、早起打卡
> > > 时间:2021-11-14 20:00:50
> > > 登录成功
> > > [每日签到]	已签到
> > > Traceback (most recent call last):
> > > File "Mashiro2000_HeyTapTask_Community.py", line 235, in
> > > main_handler(None,None)
> > > File "Mashiro2000_HeyTapTask_Community.py", line 220, in main_handler
> > > community.start()
> > > File "Mashiro2000_HeyTapTask_Community.py", line 201, in start
> > > self.earlyBed ()
> > > File "Mashiro2000_HeyTapTask_Community.py", line 183, in earlyBed
> > > self.SignUp()
> > > File "Mashiro2000_HeyTapTask_Community.py", line 137, in SignUp
> > > response = self.sess.post(url=url,headers=headers,data=data).json()
> > > File "/usr/lib/python3.8/site-packages/requests/models.py", line 910, in json
> > > return complexjson.loads(self.text, **kwargs)
> > > File "/usr/lib/python3.8/json/**init**.py", line 357, in loads
> > > return _default_decoder.decode(s)
> > > File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
> > > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > > File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
> > > raise JSONDecodeError("Expecting value", s, err.value) from None
> > > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > > ## 执行结束... 2021-11-14 20:01:06 耗时 16 秒
> 
> 我这边测试没有问题，你再试试

还是不行，测试了一下`response = self.sess.post(url=url,headers=headers,data=data)`返回的是Response [403]

**Comment by Oreomeow** [comment]
response.text 看看，如果带 unicode

**Comment by Mashiro2000** [comment]
> 还是不行，测试了一下`response = self.sess.post(url=url,headers=headers,data=data)`返回的是Response [403]
> 
> > > > ## 开始执行... 2021-11-14 20:00:50
> > > > 鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
> > > > 该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
> > > > 青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
> > > > CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'
> > > > 任务:OPPO社区签到、早起打卡
> > > > 时间:2021-11-14 20:00:50
> > > > 登录成功
> > > > [每日签到]	已签到
> > > > Traceback (most recent call last):
> > > > File "Mashiro2000_HeyTapTask_Community.py", line 235, in
> > > > main_handler(None,None)
> > > > File "Mashiro2000_HeyTapTask_Community.py", line 220, in main_handler
> > > > community.start()
> > > > File "Mashiro2000_HeyTapTask_Community.py", line 201, in start
> > > > self.earlyBed ()
> > > > File "Mashiro2000_HeyTapTask_Community.py", line 183, in earlyBed
> > > > self.SignUp()
> > > > File "Mashiro2000_HeyTapTask_Community.py", line 137, in SignUp
> > > > response = self.sess.post(url=url,headers=headers,data=data).json()
> > > > File "/usr/lib/python3.8/site-packages/requests/models.py", line 910, in json
> > > > return complexjson.loads(self.text, **kwargs)
> > > > File "/usr/lib/python3.8/json/**init**.py", line 357, in loads
> > > > return _default_decoder.decode(s)
> > > > File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
> > > > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > > > File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
> > > > raise JSONDecodeError("Expecting value", s, err.value) from None
> > > > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > > > ## 执行结束... 2021-11-14 20:01:06 耗时 16 秒
> > 
> > 
> > 我这边测试没有问题，你再试试
> 
> 还是不行，测试了一下`response = self.sess.post(url=url,headers=headers,data=data)`返回的是Response [403]

你的国内服务器吗

**Comment by zmsnfly** [comment]
> > 还是不行，测试了一下`response = self.sess.post(url=url,headers=headers,data=data)`返回的是Response [403]
> > > > > ## 开始执行... 2021-11-14 20:00:50
> > > > > 鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
> > > > > 该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
> > > > > 青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
> > > > > CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'
> > > > > 任务:OPPO社区签到、早起打卡
> > > > > 时间:2021-11-14 20:00:50
> > > > > 登录成功
> > > > > [每日签到]	已签到
> > > > > Traceback (most recent call last):
> > > > > File "Mashiro2000_HeyTapTask_Community.py", line 235, in
> > > > > main_handler(None,None)
> > > > > File "Mashiro2000_HeyTapTask_Community.py", line 220, in main_handler
> > > > > community.start()
> > > > > File "Mashiro2000_HeyTapTask_Community.py", line 201, in start
> > > > > self.earlyBed ()
> > > > > File "Mashiro2000_HeyTapTask_Community.py", line 183, in earlyBed
> > > > > self.SignUp()
> > > > > File "Mashiro2000_HeyTapTask_Community.py", line 137, in SignUp
> > > > > response = self.sess.post(url=url,headers=headers,data=data).json()
> > > > > File "/usr/lib/python3.8/site-packages/requests/models.py", line 910, in json
> > > > > return complexjson.loads(self.text, **kwargs)
> > > > > File "/usr/lib/python3.8/json/**init**.py", line 357, in loads
> > > > > return _default_decoder.decode(s)
> > > > > File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
> > > > > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > > > > File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
> > > > > raise JSONDecodeError("Expecting value", s, err.value) from None
> > > > > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > > > > ## 执行结束... 2021-11-14 20:01:06 耗时 16 秒
> > > 
> > > 
> > > 我这边测试没有问题，你再试试
> > 
> > 
> > 还是不行，测试了一下`response = self.sess.post(url=url,headers=headers,data=data)`返回的是Response [403]
> 
> 你的国内服务器吗

国外的服务器，其他脚本可以正常跑

**Comment by Mashiro2000** [comment]
> > > 还是不行，测试了一下`response = self.sess.post(url=url,headers=headers,data=data)`返回的是Response [403]
> > > > > > ## 开始执行... 2021-11-14 20:00:50
> > > > > > 鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
> > > > > > 该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
> > > > > > 青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
> > > > > > CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'
> > > > > > 任务:OPPO社区签到、早起打卡
> > > > > > 时间:2021-11-14 20:00:50
> > > > > > 登录成功
> > > > > > [每日签到]	已签到
> > > > > > Traceback (most recent call last):
> > > > > > File "Mashiro2000_HeyTapTask_Community.py", line 235, in
> > > > > > main_handler(None,None)
> > > > > > File "Mashiro2000_HeyTapTask_Community.py", line 220, in main_handler
> > > > > > community.start()
> > > > > > File "Mashiro2000_HeyTapTask_Community.py", line 201, in start
> > > > > > self.earlyBed ()
> > > > > > File "Mashiro2000_HeyTapTask_Community.py", line 183, in earlyBed
> > > > > > self.SignUp()
> > > > > > File "Mashiro2000_HeyTapTask_Community.py", line 137, in SignUp
> > > > > > response = self.sess.post(url=url,headers=headers,data=data).json()
> > > > > > File "/usr/lib/python3.8/site-packages/requests/models.py", line 910, in json
> > > > > > return complexjson.loads(self.text, **kwargs)
> > > > > > File "/usr/lib/python3.8/json/**init**.py", line 357, in loads
> > > > > > return _default_decoder.decode(s)
> > > > > > File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
> > > > > > obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > > > > > File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
> > > > > > raise JSONDecodeError("Expecting value", s, err.value) from None
> > > > > > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > > > > > ## 执行结束... 2021-11-14 20:01:06 耗时 16 秒
> > > > 
> > > > 
> > > > 我这边测试没有问题，你再试试
> > > 
> > > 
> > > 还是不行，测试了一下`response = self.sess.post(url=url,headers=headers,data=data)`返回的是Response [403]
> > 
> > 
> > 你的国内服务器吗
> 
> 国外的服务器，其他脚本可以正常跑
emmm，我想一下，看看怎么解决

**Comment by Mashiro2000** [comment]
其它脚本是OPPO商城的，早起打卡是OPPO社区的，可能是服务器的原因

**Comment by zmsnfly** [comment]
> 其它脚本是OPPO商城的，早起打卡是OPPO社区的，可能是服务器的原因

可能是这样，看来只能换个环境了

**Comment by Mashiro2000** [comment]
重新拉取，在运行看看，，好像是一个bug

**Comment by zmsnfly** [comment]
> 重新拉取，在运行看看，，好像是一个bug

不行，还是返回<Response [403]>，估计是网络环境的问题。

**Comment by Mashiro2000** [comment]
> > 重新拉取，在运行看看，，好像是一个bug
> 
> 不行，还是返回<Response [403]>，估计是网络环境的问题。

已证明，是国外服务器原因
