### ISSUE TITLE
刚更新了还是不行啊提示json数据不全

### ISSUE THREAD

**Issue by fenglatiao** [Mashiro2000/HeyTapTask#115]
任务:欢太任务中心
时间:2021-11-14 20:30:26
账号: 
状态: 取消登录
原因: json数据不齐全
账号: 
状态: 取消登录
原因: json数据不齐全
钉钉机器人 服务启动
企业微信 APP 服务启动
tg 服务启动
钉钉机器人 推送成功！
企业微信推送成功！
tg 推送成功！

**Comment by Wittoy** [comment]
青龙最新版本？

**Comment by Mashiro2000** [comment]
> 任务:欢太任务中心 时间:2021-11-14 20:30:26 账号: 状态: 取消登录 原因: json数据不齐全 账号: 状态: 取消登录 原因: json数据不齐全 钉钉机器人 服务启动 企业微信 APP 服务启动 tg 服务启动 钉钉机器人 推送成功！ 企业微信推送成功！ tg 推送成功！

青龙最新版本，好像有些诡异，好好检查下，是否在本项目内配置CK信息

**Comment by Mashiro2000** [comment]
> 任务:欢太任务中心 时间:2021-11-14 20:30:26 账号: 状态: 取消登录 原因: json数据不齐全 账号: 状态: 取消登录 原因: json数据不齐全 钉钉机器人 服务启动 企业微信 APP 服务启动 tg 服务启动 钉钉机器人 推送成功！ 企业微信推送成功！ tg 推送成功！

可以提供下你的CK吗，我这边测试下
463022229

**Comment by Mashiro2000** [comment]
> 任务:欢太任务中心 时间:2021-11-14 20:30:26 账号: 状态: 取消登录 原因: json数据不齐全 账号: 状态: 取消登录 原因: json数据不齐全 钉钉机器人 服务启动 企业微信 APP 服务启动 tg 服务启动 钉钉机器人 推送成功！ 企业微信推送成功！ tg 推送成功！

你的user有填写吗

**Comment by fenglatiao** [comment]
> > 任务:欢太任务中心 时间:2021-11-14 20:30:26 账号: 状态: 取消登录 原因: json数据不齐全 账号: 状态: 取消登录 原因: json数据不齐全 钉钉机器人 服务启动 企业微信 APP 服务启动 tg 服务启动 钉钉机器人 推送成功！ 企业微信推送成功！ tg 推送成功！
> 
> 青龙最新版本，好像有些诡异，好好检查下，是否在本项目内配置CK信息

最新版本，user填写了，

**Comment by fenglatiao** [comment]
> > 任务：太任务中心时间：2021-11-14 20：30:26 账号：状态：取消登录原因：json数据不欢欢账号：状态：取消登录原因：json数据不监听钉钉机器人服务启动企业微信APP服务启动 tg 服务启动 钉钉机器人成功！企业微信成功！ tg 成功！
> 
> 你的用户有填写吗

写了ck发您QQ邮箱了 最新版本青龙

**Comment by Mashiro2000** [comment]
> > > 任务：太任务中心时间：2021-11-14 20：30:26 账号：状态：取消登录原因：json数据不欢欢账号：状态：取消登录原因：json数据不监听钉钉机器人服务启动企业微信APP服务启动 tg 服务启动 钉钉机器人成功！企业微信成功！ tg 成功！
> > 
> > 
> > 你的用户有填写吗
> 
> 写了ck发您QQ邮箱了 最新版本青龙

重新拉取脚本，再次运行看看

**Comment by solodarker** [comment]
> > 任务:欢太任务中心 时间:2021-11-14 20:30:26 账号: 状态: 取消登录 原因: json数据不齐全 账号: 状态: 取消登录 原因: json数据不齐全 钉钉机器人 服务启动 企业微信 APP 服务启动 tg 服务启动 钉钉机器人 推送成功！ 企业微信推送成功！ tg 推送成功！
> 
> 你的user有填写吗

2.9.7的青龙也有这个提示

**Comment by github-sxw** [comment]
用vim编辑下ql/scripts/Mashiro2000_HeyTapTask下面的HT_account.py就OK了
