### ISSUE TITLE
json数据不齐全

### ISSUE THREAD

**Issue by lfscqk67** [Mashiro2000/HeyTapTask#116]
我也出现这问题了，大佬帮忙看看
![image](https://user-images.githubusercontent.com/37235589/141682842-6ac5c734-376f-45be-9a31-3ab176d90d9c.png)

**Comment by Mashiro2000** [comment]
重新拉取，试试看，刚刚更新了代码

**Comment by lfscqk67** [comment]
> 重新拉取，试试看，刚刚更新了代码

还是那样。。

**Comment by Mashiro2000** [comment]
> > 重新拉取，试试看，刚刚更新了代码
> 
> 还是那样。。

最小脚本也是这样吗

**Comment by Mashiro2000** [comment]
最新版青龙的原因，我得去研究下怎么整

**Comment by dark748001** [comment]
没有.还是10.2的版本.没有更新最新的

**Comment by StephenSSR** [comment]
2.9.9版本也是

**Comment by charmok** [comment]
保存不了CK了，每次修改account.py时候，会自动生成另外一个以Mashiro2000_HeyTapTask开头的account文件
