### ISSUE TITLE
提供活动

### ISSUE THREAD

**Issue by 7214978** [Mashiro2000/HeyTapTask#117]
提供几个活动链接，大佬有空看下
https://activity-cdo.heytapimage.com/cdo-activity/staticActivity/PlmYLM/htmls/index.html
https://hd.oppo.com/act/m/2021013/index.html  活动日期过了还是可以抽的
https://hd.oppo.com/act/m/2021/memberoppojifen/index.html
https://hd.oppo.com/act/m/2021/jifenzhuanpan/index.html
https://hd.oppo.com/act/m/2021/zhibogonglue/index.html
https://hd.oppo.com/act/m/2020/realmechannejifendui/index.html
https://hd.oppo.com/act/m/2020/iot-meirichoujiang2/index.html
https://hd.oppo.com/act/m/2021/huantaichongfenhuodo/index.html
https://hd.oppo.com/act/m/2019/jifenfanbei/index.html

**Comment by Mashiro2000** [comment]
好的，
