### ISSUE TITLE
青龙面板提示Json不全解决方法

### ISSUE THREAD

**Issue by LondyGhost** [Mashiro2000/HeyTapTask#119]
不知道青龙作者更新了什么。或者本项目作者更新了文件折叠，和青龙起了冲突。现在HT_account.py是在/ql/scripts/Mashiro2000_HeyTapTask   这个文件夹下面。
如果在青龙面板的脚本管接修改HT_account.py，青龙会把HT_account.py另存为Mashiro2000_HeyTapTask-HT_account.py

解决方法就是。退出容器。（容器里操作vi也行，不过不如vim好用）。找到宿主上面的HT_account.py文件 vim修改后再保存就好了。顺便复制一份HT_account.py到/ql/scripts  这个文件夹里。

**Comment by Mashiro2000** [comment]
这个是青龙的原因，正在寻找解决方案，这个方案是可行的，但部分用户不懂Linux

**Comment by 7214978** [comment]
pc端修改Mashiro2000_HeyTapTask文件夹里边的HT_account.py文件保存不会生效，暂时用移动端修改就可以保存了，可以用PC浏览器F12改设备型号。

**Comment by FKDD23** [comment]
一样 
账号: 
状态: 取消登录
原因: json数据不齐全
账号: 
状态: 取消登录
原因: json数据不齐全

**Comment by FKDD23** [comment]
> 不知道青龙作者更新了什么。或者本项目作者更新了文件折叠，和青龙起了冲突。现在HT_account.py是在/ql/scripts/Mashiro2000_HeyTapTask 这个文件夹下面。 如果在青龙面板的脚本管接修改HT_account.py，青龙会把HT_account.py另存为Mashiro2000_HeyTapTask-HT_account.py
> 
> 解决方法就是。退出容器。（容器里操作vi也行，不过不如vim好用）。找到宿主上面的HT_account.py文件 vim修改后再保存就好了。顺便复制一份HT_account.py到/ql/scripts 这个文件夹里。

按照这个解决了

**Comment by NealJun** [comment]
> 不知道青龙作者更新了什么。或者本项目作者更新了文件折叠，和青龙起了冲突。现在HT_account.py是在/ql/scripts/Mashiro2000_HeyTapTask 这个文件夹下面。 如果在青龙面板的脚本管接修改HT_account.py，青龙会把HT_account.py另存为Mashiro2000_HeyTapTask-HT_account.py
> 
> 解决方法就是。退出容器。（容器里操作vi也行，不过不如vim好用）。找到宿主上面的HT_account.py文件 vim修改后再保存就好了。顺便复制一份HT_account.py到/ql/scripts 这个文件夹里。

请问宿主是什么，在哪里，只修改scripts中的account.py可行吗

**Comment by xinxuanjvshi** [comment]
我是老版本青龙，只更新了脚本之后也出现最后提示json格式不全退出登录，但是任务都正常执行了

**Comment by xinxuanjvshi** [comment]
> 我是老版本青龙，只更新了脚本之后也出现最后提示json格式不全退出登录，但是任务都正常执行了

搞错了是account文件里没有删掉未未填写的user ck UA导致的，删掉后就没有提示了

**Comment by github-sxw** [comment]
用vim编辑下ql/scripts/Mashiro2000_HeyTapTask下面的HT_account.py就OK了

**Comment by gdw1986** [comment]
编辑了还是没用啊

**Comment by LondyGhost** [comment]
> 编辑了还是没用啊

你是怎么操作的？

**Comment by FairyWorld** [comment]
> 不知道青龙作者更新了什么。或者本项目作者更新了文件折叠，和青龙起了冲突。现在HT_account.py是在/ql/scripts/Mashiro2000_HeyTapTask 这个文件夹下面。 如果在青龙面板的脚本管接修改HT_account.py，青龙会把HT_account.py另存为Mashiro2000_HeyTapTask-HT_account.py
> 
> 解决方法就是。退出容器。（容器里操作vi也行，不过不如vim好用）。找到宿主上面的HT_account.py文件 vim修改后再保存就好了。顺便复制一份HT_account.py到/ql/scripts 这个文件夹里。

试过了还是不行

**Comment by okmqazqwerty** [comment]
json不全是因为初始格式有一个空的账号，之前青龙读取到空的字段可能是丢弃了，但更新以后认为是一个名称（空）的账号，所以提示json不全。删掉示例的后面空白三行就行

**Comment by bby0** [comment]
> 不知道青龙作者更新了什么。或者本项目作者更新了文件折叠，和青龙起了冲突。现在HT_account.py是在/ql/scripts/Mashiro2000_HeyTapTask 这个文件夹下面。 如果在青龙面板的脚本管接修改HT_account.py，青龙会把HT_account.py另存为Mashiro2000_HeyTapTask-HT_account.py
> 
> 解决方法就是。退出容器。（容器里操作vi也行，不过不如vim好用）。找到宿主上面的HT_account.py文件 vim修改后再保存就好了。顺便复制一份HT_account.py到/ql/scripts 这个文件夹里。

没有Mashiro2000_HeyTapTask这个文件夹

**Comment by 56warmers** [comment]
青龙这次更新还是有意义的，以前许多库的定时任务py都放在/ql/scripts文件夹下，确实很乱，更新后能按库区分开
