### ISSUE TITLE
青龙怎么使用配置文件

### ISSUE THREAD

**Issue by github5143** [Mashiro2000/HeyTapTask#120]
## 开始执行... 2021-11-15 10:48:05

`sendNotify.py`不存在,尝试进行下载...
`HT_account.py`不存在,尝试进行下载...

鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

发生下载行为,应退出程序，编辑配置文件

大佬，我拉库到青龙了，按照教程说要把ck转移到配置文件中，我就scripts的sendNotify.py和HT_account.py脚本转移到config后，运行就提示这个，是我把ck转移到配置文件这一步出错了吗？

**Comment by 7L787** [comment]
你直接在这两个文件配置，不要使用config这个

**Comment by github5143** [comment]
对的，在脚本管理那里配置好了，已经在正常运行了。但是推送有点小问题
sendNotify.py我配置好了，但是推送还是发在我jd的那个推送小组，就是不发我设置好的heytap小组。我用的是企业微信推送，这个有办法解决吗？

**Comment by 7L787** [comment]
server 酱我用的是那个，没试过用企业微信

**Comment by Mashiro2000** [comment]
> 对的，在脚本管理那里配置好了，已经在正常运行了。但是推送有点小问题 sendNotify.py我配置好了，但是推送还是发在我jd的那个推送小组，就是不发我设置好的heytap小组。我用的是企业微信推送，这个有办法解决吗？

用环境变量

**Comment by github5143** [comment]
> > 对的，在脚本管理那里配置好了，已经在正常运行了。但是推送有点小问题 sendNotify.py我配置好了，但是推送还是发在我jd的那个推送小组，就是不发我设置好的heytap小组。我用的是企业微信推送，这个有办法解决吗？
> 
> 用环境变量

环境变量怎么使用，能简单指点一下吗？

**Comment by 592732377** [comment]
> 对的，在脚本管理那里配置好了，已经在正常运行了。但是推送有点小问题 sendNotify.py我配置好了，但是推送还是发在我jd的那个推送小组，就是不发我设置好的heytap小组。我用的是企业微信推送，这个有办法解决吗？

企业微信推送可以使用青龙的环境变量，但是要将`QYWX_AM`中的消息“消息类型”参数空置(空置默认进行文本消息发送)，不然sendNotify.py会报错。
不使用环境变量就直接修改目录下的sendNotify.py，然后再把它加入到ql repo 黑名单中，不然每次更新都会覆盖。
