### ISSUE TITLE
空账号 跳过。是怎么回事？

### ISSUE THREAD

**Issue by syymo** [Mashiro2000/HeyTapTask#122]
![image](https://user-images.githubusercontent.com/26571594/141923117-939f819a-c018-454e-82d4-1db2bd5f7b28.png)

**Comment by Tomatofanfan** [comment]
我也是这个问题。。

**Comment by hu516** [comment]
同有这个问题

**Comment by requireCool** [comment]
把`HT_account.py`里的空项删了

**Comment by Tomatofanfan** [comment]
我把每个任务里面末尾4行删了，现在没提示这个了
        elif not all(each.values()):
            notify("账号:空账户\t状态:跳过")
        else:
            notify(f"账号: {each['user']}\n状态: 取消登录\n原因: json数据不齐全")

**Comment by Mashiro2000** [comment]
emmm，代码逻辑是没问题的，，，你是没有任何账户吗

**Comment by AzazelYui** [comment]
脚本管理里，编辑CK到HT_account.py后，保存后还是空白。但是会生成一个Mashiro2000_HeyTapTask_account.py，这是正常的吗？
任务日志还是提示空账户

**Comment by d8899p** [comment]
我也是出现这个问题，也不知道怎么解决的

**Comment by syymo** [comment]
> emmm，代码逻辑是没问题的，，，你是没有任何账户吗

我前一个版本是好的，自从前天拉了最新的就这样了，有两个账号

**Comment by syymo** [comment]
> emmm，代码逻辑是没问题的，，，你是没有任何账户吗

![image](https://user-images.githubusercontent.com/26571594/142095839-d2fb2207-e37f-4886-9379-9285772ff296.png)

**Comment by yaowans** [comment]
把HT_account.py复制到文件夹中，如图
![image](https://user-images.githubusercontent.com/21300948/142135395-223631d7-d291-4c67-829f-ac84ca249648.png)

**Comment by syymo** [comment]
> 把HT_account.py复制到文件夹中，如图 ![image](https://user-images.githubusercontent.com/21300948/142135395-223631d7-d291-4c67-829f-ac84ca249648.png)

不知道为什么，改了并且保存之后，再次进去就被清空了

**Comment by requireCool** [comment]
> > 把HT_account.py复制到文件夹中，如图 ![image](https://user-images.githubusercontent.com/21300948/142135395-223631d7-d291-4c67-829f-ac84ca249648.png)
> 
> 不知道为什么，改了并且保存之后，再次进去就被清空了

保存异常是青龙之前版本的bug，升级到2.10.8即可

**Comment by syymo** [comment]
> 把HT_account.py复制到文件夹中，如图 ![image](https://user-images.githubusercontent.com/21300948/142135395-223631d7-d291-4c67-829f-ac84ca249648.png)

这样可以解决。
