### ISSUE TITLE
作者您好，刚才因未给所有脚本设置触发器报错，现在已添加触发器仍然执行失败，但未发现问题，ck根据wiki教程之保留了source_type、TOKENSID、app_param三项

### ISSUE THREAD

**Issue by lisonglin980** [Mashiro2000/HeyTapTask#126]
![image](https://user-images.githubusercontent.com/68982838/142219426-49134208-f652-4ad3-a5e5-a12af777f4c1.png)
![image](https://user-images.githubusercontent.com/68982838/142219512-400026de-c789-420b-8331-4b3975b1108d.png)

**Comment by lisonglin980** [comment]
总共添加了10个触发器，分别是CollectionCard、Double11、BattleForHeyTap、OnePlusJYStation、Community、	
TimingCash、DailyCash、ChockInEarly、BattleForRealMe、TaskCenter，定时都是复制脚本里面的时间，然后刚才我把push+推送删掉后重新测试，报错不一样了
执行日志
START RequestId:12eb9389-dba7-46c3-9920-b1a9297bd960

ERROR RequestId:12eb9389-dba7-46c3-9920-b1a9297bd960 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 10, in main_handler\n    taskName = import_module(event['TriggerName'])\nKeyError: 'TriggerName'","statusCode":430}
不知道哪里出错了

**Comment by lisonglin980** [comment]
![image](https://user-images.githubusercontent.com/68982838/142222245-f544a82e-248f-40f9-92f3-b1e9c4a93bb4.png)

**Comment by lisonglin980** [comment]
![image](https://user-images.githubusercontent.com/68982838/142222804-bf8b8f13-2d25-4fbc-8218-60226ad80517.png)
对不起作者，这句话没理解到，意思是要等触发器触发了才有这个参数，测试才不会报错吗

**Comment by Mashiro2000** [comment]
> ![image](https://user-images.githubusercontent.com/68982838/142222804-bf8b8f13-2d25-4fbc-8218-60226ad80517.png) 对不起作者，这句话没理解到，意思是要等触发器触发了才有这个参数，测试才不会报错吗

对，或者切换为旧版编辑器，选择timer触发器
