### ISSUE TITLE
打卡消耗“打卡减扣积分”被扣了500

### ISSUE THREAD

**Issue by cdj8105** [Mashiro2000/HeyTapTask#127]
打卡消耗“打卡减扣积分”是什么？好像是oppo社区的，今天上午网络有问题，刚弄好。发现明天扣的500没补回来，打开oppo社区app也没发现怎么操作啊…

**Comment by Mashiro2000** [comment]
检查下运行日志，看看是什么原因，我这边完全正常，
现在打卡实现了OPPO商城的早睡打卡以及OPPO社区的早起打卡，一天会报名两个打卡，第二天再打卡
