### ISSUE TITLE
报错NameError: name 'notifyBlackList' is not defined

### ISSUE THREAD

**Issue by ssrgd** [Mashiro2000/HeyTapTask#13]
使用云函数和青龙部署都是提示一样的错误，请大佬解惑

## 开始执行... 2021-09-28 11:35:58

CK配置 -> 脚本管理 -> 搜索`HT_config`关键字 -> 编辑

更新配置文件或检测CK
任务:任务中心
时间:2021-09-28 11:35:59
Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_TaskCenter.py", line 604, in <module>
    main(None,None)
  File "Mashiro2000_HeyTapTask_TaskCenter.py", line 600, in main
    if not os.path.basename(__file__)[:-3] in notifyBlackList:
NameError: name 'notifyBlackList' is not defined

## 执行结束... 2021-09-28 11:35:59 耗时 1 秒

**Comment by awordx** [comment]
我也是报了这个错，不知道咋办

**Comment by Mashiro2000** [comment]
> 账号多了就报这个错误

这个不是账号多导致报错，是因为配置文件里没有定义notifyBlackList = []
