### ISSUE TITLE
使用网页版抓的cookie也可以使用

### ISSUE THREAD

**Issue by atyvcn** [Mashiro2000/HeyTapTask#130]
我把ck验证字段的函数删除，发现使用网页版抓取的ck能够正常使用而昨天用小黄鸟今天却发现老是提示auth token is empty

**Comment by Mashiro2000** [comment]
> 我把ck验证字段的函数删除，发现使用网页版抓取的ck能够正常使用而昨天用小黄鸟今天却发现老是提示auth token is empty

所有活动都可运行吗，没记错的话，web不提供`app_param=xxxx`字段

**Comment by atyvcn** [comment]
> > 我把ck验证字段的函数删除，发现使用网页版抓取的ck能够正常使用而昨天用小黄鸟今天却发现老是提示auth token is empty
> 
> 所有活动都可运行吗，没记错的话，web不提供`app_param=xxxx`字段

**Comment by Mashiro2000** [comment]
好的，后续我再验证

**Comment by atyvcn** [comment]
好的。

**Comment by atyvcn** [comment]
![ZF~N CXIQTT67NE 1ZM8HBK](https://user-images.githubusercontent.com/28555862/142559408-7df68b6d-d302-44f2-b1d5-6eaa93a45eef.png)
![)RB)T$%@IBPMH@}6BMX)$PJ](https://user-images.githubusercontent.com/28555862/142559420-21ebea79-a377-4fcb-b19f-5397b88f653d.png)
![X2$WH`NJ`Z IL68BF1L~2O5](https://user-images.githubusercontent.com/28555862/142559425-f3c4588d-bdbb-47c5-94b2-c6b6bd1ee3f7.png)
![(D12 CO2HQPQI 0AZTCA%@M](https://user-images.githubusercontent.com/28555862/142559532-56ef45a1-be95-4339-b826-a61ea419e68f.png)

回笑看今朝和缘起似梦绕都是同一个账号，是我昨天抓取的

**Comment by caichunyu** [comment]
我今天新注册了一个账号，遇到了和你回笑看今朝这个号一样的问题，我重新登陆了下再抓包就解决了

**Comment by atyvcn** [comment]
> 我今天新注册了一个账号，遇到了和你回笑看今朝这个号一样的问题，我重新登陆了下再抓包就解决了

我说的不是这个问题，我说的是不需要去抓取APP的ck 网页版的也行

**Comment by Todddday** [comment]
> > 我今天新注册了一个账号，遇到了和你回笑看今朝这个号一样的问题，我重新登陆了下再抓包就解决了
> 
> 我说的不是这个问题，我说的是不需要去抓取APP的ck 网页版的也行

我想问一下，网页版的token需要多少个属性呢，我用了网页版的ck，然后还报json参数不足。
