### ISSUE TITLE
青龙面板拉库导致sendNotify.py被重置

### ISSUE THREAD

**Issue by LibertyLancer** [Mashiro2000/HeyTapTask#131]
青龙面板每次拉库之后sendNotify.py里填写的企业微信推送内容就被清空了，怎么设置才能保持？
![QQ截图20211119110732](https://user-images.githubusercontent.com/75461565/142558341-d6090d54-8bca-4957-9b32-b5fd6d158a35.jpg)

**Comment by Mashiro2000** [comment]
使用环境变量

**Comment by Mashiro2000** [comment]
![image](https://user-images.githubusercontent.com/40681822/142558528-1721201d-419f-4ecc-84dc-1026a7eb0f52.png)

**Comment by Mashiro2000** [comment]
或者在config.sh里填写
以钉钉机器人为例
```
export DD_BOT_TOKEN="xxxxx"
export DD_BOT_SECRET="xxxx"
```

**Comment by Oreomeow** [comment]
`curtinlv` 的库有自动下载覆盖行为
