### ISSUE TITLE
配置了Ht_cookie，账号没被检测到

### ISSUE THREAD

**Issue by zhongzeqing** [Mashiro2000/HeyTapTask#132]
大佬帮忙看看是什么问题
![image](https://user-images.githubusercontent.com/43203407/142562020-23facc37-5484-4f26-89f8-770471d68e63.png)
![Uploading image.png…]()

**Comment by Mashiro2000** [comment]
配置界面，我看看

**Comment by Mashiro2000** [comment]
搜索HT_account.py后的截图，

**Comment by zry9815** [comment]
> 搜索HT_account.py后的截图，
![微信截图_20211119125818](https://user-images.githubusercontent.com/67041916/142567474-239588a5-3938-4100-ac84-9f60cc966d9c.png)

重新拉库更新了下以后也出现上面这种情况

**Comment by zhongzeqing** [comment]
![image](https://user-images.githubusercontent.com/43203407/142567996-ffc54881-e848-4872-a270-e16a1f19de29.png)
和楼上一样

**Comment by zhongzeqing** [comment]
> 搜索HT_account.py后的截图，

![image](https://user-images.githubusercontent.com/43203407/142578584-fcef1bc4-8594-4d40-b420-d74c6deaeb4c.png)

**Comment by Mashiro2000** [comment]
> > 搜索HT_account.py后的截图，
> > ![微信截图_20211119125818](https://user-images.githubusercontent.com/67041916/142567474-239588a5-3938-4100-ac84-9f60cc966d9c.png)
> 
> 重新拉库更新了下以后也出现上面这种情况

选择文件夹下的，+号点击以下，里面有，这是青龙改版的缘故

**Comment by Eternity-luo** [comment]
![Screenshot_20211120025825](https://user-images.githubusercontent.com/72162184/142676782-467346aa-b626-41cd-9c51-c5cea96316ed.jpg)
也出现了是空账号😂青龙2.10.2

**Comment by wintsa123** [comment]
我也出现了同样的问题

**Comment by Mashiro2000** [comment]
![](https://z3.ax1x.com/2021/11/20/IqXvFO.png)

**Comment by Mashiro2000** [comment]
> ![](https://z3.ax1x.com/2021/11/20/IqXvFO.png)

**Comment by Mashiro2000** [comment]
![](https://z3.ax1x.com/2021/11/20/IqXvFO.png)
