### ISSUE TITLE
拉库时出现文件错误

### ISSUE THREAD

**Issue by cike-567** [Mashiro2000/HeyTapTask#133]
<img width="635" alt="屏幕截图 2021-11-19 180603" src="https://user-images.githubusercontent.com/68531942/142608131-b1ebbdfa-e89e-4a88-940a-5824a4453355.png">
<img width="313" alt="屏幕截图 2021-11-19 180529" src="https://user-images.githubusercontent.com/68531942/142608295-da67c761-3146-433d-a87c-9b46cee2f7e1.png">

**Comment by Mashiro2000** [comment]
非本项目脚本问题，我这边测试，是正常的

**Comment by cike-567** [comment]
我用国内阿里云的机子，遇到几次了。下次我试试镜像站拉取。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 晚上10:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mashiro2000/HeyTapTask] 拉库时出现文件错误 (Issue #133)






非本项目脚本问题，我这边测试，是正常的

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.
