### ISSUE TITLE
无法检测用户数据

### ISSUE THREAD

**Issue by a54731037** [Mashiro2000/HeyTapTask#137]
![image](https://user-images.githubusercontent.com/63081570/142710964-302debde-87e1-4c08-b644-19c69fd9c604.png)
![image](https://user-images.githubusercontent.com/63081570/142710998-779192bc-fe3c-4a1d-a821-3d125a70c4d4.png)

**Comment by Mashiro2000** [comment]
参考:[](https://github.com/Mashiro2000/HeyTapTask/issues/132#issuecomment-974586219)

**Comment by a54731037** [comment]
![image](https://user-images.githubusercontent.com/63081570/142713668-d65eab4a-eae6-4c8c-873e-ef86c513ffec.png)
我之前就是这样的，19号还可以 20号就不行了

**Comment by Mashiro2000** [comment]
> ![image](https://user-images.githubusercontent.com/63081570/142713668-d65eab4a-eae6-4c8c-873e-ef86c513ffec.png) 我之前就是这样的，19号还可以 20号就不行了

能让我远程操作下你的青龙面板吗，我看下具体原因
