### ISSUE TITLE
配置账户信息的时候总是在第19行报错，

### ISSUE THREAD

**Issue by wangxinlei777** [Mashiro2000/HeyTapTask#138]
![image](https://user-images.githubusercontent.com/55648591/142798585-20fc0438-a667-439b-a5a0-4fdc26992cd6.png)
无论19行有没有代码都会报错

**Comment by Mashiro2000** [comment]
问题解决了吗

**Comment by Oreomeow** [comment]
但凡点一下部署就不会问了

**Comment by wangxinlei777** [comment]
> 但凡点一下部署就不会问了

我既然问了，必然是已经部署过了

**Comment by wangxinlei777** [comment]
> 问题解决了吗

解决了，但是不知道怎么解决的，重新新建了一个好了，谢谢你
