### ISSUE TITLE
NameError: name 'notifyBlackList' is not defined，多账户导致的吗？

### ISSUE THREAD

**Issue by wanrenyuxin** [Mashiro2000/HeyTapTask#14]
## 开始执行... 2021-09-28 13:03:43

CK配置 -> 脚本管理 -> 搜索`HT_config`关键字 -> 编辑

更新配置文件或检测CK
任务:欢太积分大乱斗
时间:2021-09-28 13:03:46
Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_BattleForHeyTap.py", line 344, in <module>
    main(None,None)
  File "Mashiro2000_HeyTapTask_BattleForHeyTap.py", line 340, in main
    if not os.path.basename(__file__)[:-3] in notifyBlackList:
NameError: name 'notifyBlackList' is not defined
添加了notifyBlackList = []也不行，执行任务还是这样子显示

**Comment by wanrenyuxin** [comment]
青龙2.95

**Comment by Mashiro2000** [comment]
> 青龙2.95

你把欢太的CK备份下(先复制出来放到txt里)
然后拷贝下[HT_config.py](https://github.com/Mashiro2000/HeyTapTask/blob/main/HT_config.py)覆盖掉青龙的HT_config.py里的内容

**Comment by Mashiro2000** [comment]
我去测试康康

**Comment by 166679551** [comment]
> 我去测试康康

8个号就出错改成三个就自己好了

**Comment by Mashiro2000** [comment]
> > 我去测试康康
> 
> 8个号就出错改成三个就自己好了

你把`Mashiro2000_HeyTapTask_BattleForRealMe.py`的代码，截图我看看，最后面

**Comment by Mashiro2000** [comment]
我这边测试好像没问题

**Comment by 166679551** [comment]
> 我这边测试好像没问题

你加我昵称的qq我发你面板账号密码直接看

**Comment by Mashiro2000** [comment]
已解决，不正确的json格式导致导包错误

**Comment by Mashiro2000** [comment]
八个账号仍可正常运行，请注意json格式

**Comment by Mashiro2000** [comment]
> > > 我去测试康康
> > 
> > 
> > 8个号就出错改成三个就自己好了
> 
> 我一个都出错。。

注意下json是否有误
