### ISSUE TITLE
空账号问题

### ISSUE THREAD

**Issue by wintsa123** [Mashiro2000/HeyTapTask#140]
#13
![微信图片_20211123122036](https://user-images.githubusercontent.com/47288630/142970853-f257884c-b62d-4c3d-a295-084833aa0346.png)
![微信图片_20211123122032](https://user-images.githubusercontent.com/47288630/142970864-8119e0c7-ba75-4f97-9922-45fb40654497.png)
7 
配置正常，21号左右开始出现这个问题

**Comment by Mashiro2000** [comment]
#132

**Comment by Mashiro2000** [comment]
不在文件HeyTapTask目录下

**Comment by wintsa123** [comment]
重新同步吗，还是在青龙的script下复制脚本到script下的HeyTapTask目录？

**Comment by wintsa123** [comment]
已经成功识别账户了，谢谢up

**Comment by wintsa123** [comment]
![微信图片_20211123123614](https://user-images.githubusercontent.com/47288630/142971911-43fbaefe-184a-4172-aa4b-f70fa63c59fd.png)
这是为什么？

**Comment by wintsa123** [comment]
已经好了，抓包地址错了，现在已经正常了
