### ISSUE TITLE
今天发现RealMe积分大乱斗有几个活动没执行，看了一下日志报错了

### ISSUE THREAD

**Issue by 344108150** [Mashiro2000/HeyTapTask#145]
如题，麻烦大佬给看看
![image](https://user-images.githubusercontent.com/90685197/143523213-9e8a13d8-36f3-4665-a4cc-2b47f503b29f.png)
![image](https://user-images.githubusercontent.com/90685197/143523228-9930f573-2fd2-4230-b948-d002cc798697.png)

**Comment by Mashiro2000** [comment]
可能是网络延迟，，重新运行看看，我这边没问题
