### ISSUE TITLE
TOKENSID 这个cookie没有找到

### ISSUE THREAD

**Issue by Avondrix** [Mashiro2000/HeyTapTask#146]
<img width="592" alt="Screen Shot 2021-11-26 at 13 59 51" src="https://user-images.githubusercontent.com/62943035/143534291-daa2b8bb-9e20-4a23-a524-cbf80e7ca84d.png">
<img width="247" alt="Screen Shot 2021-11-26 at 14 02 03" src="https://user-images.githubusercontent.com/62943035/143534354-255d1b44-9cb3-489e-b979-b599de70b541.png">

**Comment by Mashiro2000** [comment]
重新抓包
