### ISSUE TITLE
怎么关闭欢太早起和社区早起？

### ISSUE THREAD

**Issue by cdj8105** [Mashiro2000/HeyTapTask#149]
感觉投入500，换来多了二三个风险性很大。由于网络原因亏了1000了。
是不是把这两项禁用就行了？
<a href="https://imgtu.com/i/omtm6A"><img src="https://z3.ax1x.com/2021/11/27/omtm6A.png" alt="omtm6A.png" border="0" /></a>

**Comment by DGbankClouds** [comment]
要么改代码，要么青龙里面禁用
