### ISSUE TITLE
企业微信推送

### ISSUE THREAD

**Issue by nice2cu1** [Mashiro2000/HeyTapTask#16]
企业微信的推送配置需要怎么填写？能说一下格式吗

**Comment by Mashiro2000** [comment]
这个不需要填写，青龙面板的配信功能暂时不可用，其它运行方案，仍可运行

**Comment by nice2cu1** [comment]
> 这个不需要填写，青龙面板的配信功能暂时不可用，其它运行方案，仍可运行

我是部署在云函数上，不是青龙面板
