### ISSUE TITLE
欢太积分显示用户未登录

### ISSUE THREAD

**Issue by chirks** [Mashiro2000/HeyTapTask#17]
欢太积分大乱斗

任务:欢太积分大乱斗
时间:2021-09-28 14:13:58
xx登录成功
[浏览realme专区] 用户未登录
[浏览一加专区] 用户未登录
[浏览潮流好物专区] 用户未登录
[观看realme直播] 用户未登录
[观看一加直播] 用户未登录
[浏览超级宠粉专区] 用户未登录
[浏览真我GT Neo2] 用户未登录

任务:欢太每日现金
时间:2021-09-28 12:30:01
xx登录成功
浏览商品	已领取
浏览秒杀专区	已领取
分享商品	已领取
观看直播	已领取
浏览领券中心	已领取
浏览签到页	已领取
浏览realme商品	已领取
浏览一加商品	已领取
浏览OPPO商品	已领取
****************************************

**Comment by Mashiro2000** [comment]
[注意顺序](https://github.com/Mashiro2000/HeyTapTask#变量值)

**Comment by Mashiro2000** [comment]
> CK顺序具有一定的要求，[点击查看](https://github.com/Mashiro2000/HeyTapTask#%E5%8F%98%E9%87%8F%E5%80%BC)

**Comment by Mashiro2000** [comment]
测试表明欢太所需CK为: `source_type`、`TOKENSID`、`app_param`,顺序不可乱

**Comment by chirks** [comment]
> 测试欢欢太需要CK为: `source_type`、`TOKENSID`、`app_param`,顺序不可乱

我看直接粘贴全部的也可以，所以我就直接全部粘贴上去的

**Comment by Mashiro2000** [comment]
> > 测试欢欢太需要CK为: `source_type`、`TOKENSID`、`app_param`,顺序不可乱
> 
> 我看直接粘贴全部的也可以，所以我就直接全部粘贴上去的

有时候，确实会这样，我也遇到过，尝试重新抓取试试看

**Comment by chirks** [comment]
> > > 测试欢欢太需要CK为: `source_type`、`TOKENSID`、`app_param`,顺序不可乱
> > 
> > 
> > 我看直接粘贴全部的也可以，所以我就直接全部粘贴上去的
> 
> 有时候，确实会这样，我也遇到过，尝试重新抓取试试看



> > > 测试欢欢太需要CK为: `source_type`、`TOKENSID`、`app_param`,顺序不可乱
> > 
> > 
> > 我看直接粘贴全部的也可以，所以我就直接全部粘贴上去的
> 
> 有时候，确实会这样，我也遇到过，尝试重新抓取试试看

我重抓了下，还是这样。。

**Comment by Mashiro2000** [comment]
方便给我CK，我拿去测试下吗

**Comment by Mashiro2000** [comment]
hide的形式发我

**Comment by chirks** [comment]
> 隐藏的形式发我

**Comment by chirks** [comment]
> 方便给我CK，我拿去测试下吗

方便，但我不知道怎么隐藏发给你

**Comment by Mashiro2000** [comment]
test

**Comment by Mashiro2000** [comment]
> > 方便给我CK，我拿去测试下吗
> 
> 方便，但我不知道怎么隐藏发给你

你联系方式给我，我看到后加你，再删除你的联系方式

**Comment by chirks** [comment]
> hide的形式发我

`[hide]`

> > > 方便给我CK，我拿去测试下吗
> > 
> > 
> > 方便，但我不知道怎么隐藏发给你
> 
> 你联系方式给我，我看到后加你，再删除你的联系方式

微信 qa4501748

**Comment by Mashiro2000** [comment]
用户已正常使用，直接粘贴CK

**Comment by WinverLemon** [comment]
老哥 这次更新完以后我也有这个问题了
