### ISSUE TITLE
云函数 send报错

### ISSUE THREAD

**Issue by LevenYi** [Mashiro2000/HeyTapTask#19]
![image](https://user-images.githubusercontent.com/50928588/135045130-8ac99647-1a5b-40e2-a0b0-1503c5bbbc64.png)
请问一下是不是要在sendNotify文件里面进行什么配置

**Comment by Mashiro2000** [comment]
在改了，目前确实存在一点

**Comment by Mashiro2000** [comment]
重新拉取即可，报错原因主要是为兼容青龙面板

**Comment by LevenYi** [comment]
> 重新拉取即可，报错原因主要是为兼容青龙面板

已解决
