### ISSUE TITLE
今天欢太问题

### ISSUE THREAD

**Issue by dark748001** [Mashiro2000/HeyTapTask#20]
![image](https://user-images.githubusercontent.com/64937100/135045986-e2d122bd-f052-4e0d-9988-47b64d5c6726.png)
jin今天执行欢太就出现这些代码

**Comment by dark748001** [comment]
![image](https://user-images.githubusercontent.com/64937100/135046073-6aa48950-70e7-4029-9697-742217b45392.png)

**Comment by Mashiro2000** [comment]
你的配置文件有更新吗
配置文件多了个`notifyBlackList = []`

**Comment by Mashiro2000** [comment]
将`notifyBlackList = []`添加到青龙面板里面`HT_config.py`任意位置也可以

**Comment by dark748001** [comment]
嗯 谢谢 我忘了更新进去 用的老的拉库命令 谢谢
