### ISSUE TITLE
信息通知问题

### ISSUE THREAD

**Issue by WinverLemon** [Mashiro2000/HeyTapTask#21]
老哥 消息通知一直失败

tg服务启动
推送失败！
local variable 'response' referenced before assignment

**Comment by Mashiro2000** [comment]
tg的话，我都没用过，我是引用青龙面板的文件，如果那个配信文件中代码有误，那就确实没办法，其它通信呢

**Comment by WinverLemon** [comment]
其他的我没试 就一直用的这个 我试试其他的吧

**Comment by Curtain-c** [comment]
找到原因了，
原青龙的tg配置信息：
代理ip关键字——TG_PROXY_HOST
curtinlv大佬的配置文件
代理ip关键字——TG_PROXY_IP
两个代理主机的关键字是不一样的，
然后亲测
在国内机条件下只有把tg的host和port参数同时填入sendNotify才能使用tg推送，（token和id在青龙面板填写即可）
我以为把面板里的TG_PROXY_HOST改成TG_PROXY_IP就能使用sendNotify的tg推送了，但还是不行
我现在把tg的配置填到了sendNotify，拉库更新时不更新sendNotify
