### ISSUE TITLE
配信文件以及拉库命令

### ISSUE THREAD

**Issue by Curtain-c** [Mashiro2000/HeyTapTask#22]
一处错误，一处建议
1.错误
readme 中 文件说明
│  sendNotify.py        # 欢太配信文件(青龙已配备,无需额外下载)
青龙提供的是sendNotify.js 不是sendNotify.py，py是拉库命令拉进去的

2.建议
我觉得如果用这个命令拉库，就不用再复制HT_config文件到scripts文件夹了，不知道大佬还是有什么更深的考虑所以没用这条命令
ql repo https://github.com/Mashiro2000/HeyTapTask.git "" "HT_config|sendNotify" "HT_config|sendNotify"

**Comment by calors** [comment]
青龙是js脚本，这个python脚本，两个不通用。

ps：大佬，加个企业微信机器人通知吧，不然每次拉库，又要重写通知的部分。

**Comment by Mashiro2000** [comment]
> 一处错误，一处建议 1.错误 readme 中 文件说明 │ sendNotify.py # 欢太配信文件(青龙已配备,无需额外下载) 青龙提供的是sendNotify.js 不是sendNotify.py，py是拉库命令拉进去的
> 
> 2.建议 我觉得如果用这个命令拉库，就不用再复制HT_config文件到scripts文件夹了，不知道大佬还是有什么更深的考虑所以没用这条命令 ql repo https://github.com/Mashiro2000/HeyTapTask.git "" "HT_config|sendNotify" "HT_config|sendNotify"

这个是有原因的。因为青龙里的sendNotify.py，里面的钉钉机器人参数有误
`sendNotify.py`钉钉token参数名:`DD_BOT_ACCESS_TOKEN`
`notify.py` 钉钉token参数名:`DD_BOT_TOKEN`
`sendNotify.js`钉钉参数名:`DD_BOT_TOKEN`
`config.sh`钉钉参数名:`DD_BOT_TOKEN`
如果使用青龙原本的`sendNotify.py`会导致无法使用钉钉机器人服务，我已经去反馈过了，在青龙面板更改前，暂时使用本项目修复过的`sendNotify.py`

**Comment by Mashiro2000** [comment]
> 青龙是js脚本，这个python脚本，两个不通用。
> 
> ps：大佬，加个企业微信机器人通知吧，不然每次拉库，又要重写通知的部分。

我去了解下，有已经完成的模板吗

**Comment by Mashiro2000** [comment]
> 青龙是js脚本，这个python脚本，两个不通用。
> 
> ps：大佬，加个企业微信机器人通知吧，不然每次拉库，又要重写通知的部分。

不是很理解你的意思，你是青龙环境吗
企业微信的`QYWX_AM`是写在哪里呢`config.sh`还是`sendNotify.py`

**Comment by calors** [comment]
> > 青龙是js脚本，这个python脚本，两个不通用。
> > ps：大佬，加个企业微信机器人通知吧，不然每次拉库，又要重写通知的部分。
> 
> 不是很理解你的意思，你是青龙环境吗 企业微信的`QYWX_AM`是写在哪里呢`config.sh`还是`sendNotify.py`

sendNotify.py 是青龙的？ 我以为是你这边加的。。python脚本里面没有微信机器人通知，js那个脚本有。。。企业微信有两种，一个是企业微信的应用通知，一种是企业微信群机器人通知。

**Comment by Mashiro2000** [comment]
我去了解下，微信配信不是很了解

**Comment by Mashiro2000** [comment]
> > > 青龙是js脚本，这个python脚本，两个不通用。
> > > ps：大佬，加个企业微信机器人通知吧，不然每次拉库，又要重写通知的部分。
> > 
> > 
> > 不是很理解你的意思，你是青龙环境吗 企业微信的`QYWX_AM`是写在哪里呢`config.sh`还是`sendNotify.py`
> 
> sendNotify.py 是青龙的？ 我以为是你这边加的。。python脚本里面没有微信机器人通知，js那个脚本有。。。企业微信有两种，一个是企业微信的应用通知，一种是企业微信群机器人通知。

我去了解下，微信配信不是很了解

**Comment by calors** [comment]
> > > > 青龙是js脚本，这个python脚本，两个不通用。
> > > > ps：大佬，加个企业微信机器人通知吧，不然每次拉库，又要重写通知的部分。
> > > 
> > > 
> > > 不是很理解你的意思，你是青龙环境吗 企业微信的`QYWX_AM`是写在哪里呢`config.sh`还是`sendNotify.py`
> > 
> > 
> > sendNotify.py 是青龙的？ 我以为是你这边加的。。python脚本里面没有微信机器人通知，js那个脚本有。。。企业微信有两种，一个是企业微信的应用通知，一种是企业微信群机器人通知。
> 
> 我去了解下，微信配信不是很了解

https://work.weixin.qq.com/api/doc/90000/90136/91770 这个是官网配置，比较简单，一个key，加一个json消息就能发送了。

**Comment by Curtain-c** [comment]
你提供的curtinlv大佬的sendNotify.py只有企业微信推送的配置信息QYWX_AM
没有企业微信机器人的QYWX_KEY
这个链接里面有微信机器人，但是没有bark的配信文件，大佬可以抽空整合一下
https://border-c.lanzoui.com/iZ8R9umr9ra

**Comment by Mashiro2000** [comment]
> > > > > 青龙是js脚本，这个python脚本，两个不通用。
> > > > > ps：大佬，加个企业微信机器人通知吧，不然每次拉库，又要重写通知的部分。
> > > > 
> > > > 
> > > > 不是很理解你的意思，你是青龙环境吗 企业微信的`QYWX_AM`是写在哪里呢`config.sh`还是`sendNotify.py`
> > > 
> > > 
> > > sendNotify.py 是青龙的？ 我以为是你这边加的。。python脚本里面没有微信机器人通知，js那个脚本有。。。企业微信有两种，一个是企业微信的应用通知，一种是企业微信群机器人通知。
> > 
> > 
> > 我去了解下，微信配信不是很了解
> 
> https://work.weixin.qq.com/api/doc/90000/90136/91770 这个是官网说明，机器人比较简单，一个key，加一个json消息就能发送了。

好的

**Comment by Mashiro2000** [comment]
已整合完成

**Comment by Mashiro2000** [comment]
> > > 青龙是js脚本，这个python脚本，两个不通用。
> > > ps：大佬，加个企业微信机器人通知吧，不然每次拉库，又要重写通知的部分。
> > 
> > 
> > 不是很理解你的意思，你是青龙环境吗 企业微信的`QYWX_AM`是写在哪里呢`config.sh`还是`sendNotify.py`
> 
> sendNotify.py 是青龙的？ 我以为是你这边加的。。python脚本里面没有微信机器人通知，js那个脚本有。。。企业微信有两种，一个是企业微信的应用通知，一种是企业微信群机器人通知。

完成了，重新拉取脚本即可

**Comment by Mashiro2000** [comment]
> 你提供的curtinlv大佬的sendNotify.py只有企业微信推送的配置信息QYWX_AM 没有企业微信机器人的QYWX_KEY 这个链接里面有微信机器人，但是没有bark的配信文件，大佬可以抽空整合一下 https://border-c.lanzoui.com/iZ8R9umr9ra

完成了，重新拉取脚本即可
