### ISSUE TITLE
更新完库以后跑脚本，企业微信机器人推送的消息只有标题没有内容

### ISSUE THREAD

**Issue by requireCool** [Mashiro2000/HeyTapTask#23]
## 更新完库以后跑脚本，企业微信机器人推送的消息只有标题没有内容
我只测试了这一种方法，其他的推送方式没试过

P.S. 虽然今天已经完成过任务了，但是推送也应该有内容才对 :(

![Screenshot_2021-09-29-23-33-57-75_e39d2c7de19156b](https://user-images.githubusercontent.com/55184050/135301433-98100940-72b4-45c7-8271-e785f6e8a55e.jpg)

**Comment by Mashiro2000** [comment]
好的，代码层面的错误，早上更改

**Comment by requireCool** [comment]
啊 更新后除了TaskCenter.py以外，其他脚本还是要从HT_Config里Import allMess和notify，这会导致报错

**Comment by Mashiro2000** [comment]
> 啊 更新后除了TaskCenter.py以外，其他脚本还是要从HT_Config里Import allMess和notify，这会导致报错

太粗心了，我的错误
