### ISSUE TITLE
请问这是什么原因啊 ？是HT_config里少配置吗？

### ISSUE THREAD

**Issue by 344108150** [Mashiro2000/HeyTapTask#24]
Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_DailyCash.py", line 22, in <module>
    from HT_config import allMess,downFlag,notifyBlackList,isLottery,logger,notify
ImportError: cannot import name 'allMess' from 'HT_config' (/ql/scripts/HT_config.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_DailyCash.py", line 24, in <module>
    logger.info('近期代码发生重构,请前往 https://github.com/Mashiro2000/HeyTapTask 查看更新')
NameError: name 'logger' is not defined

**Comment by Mashiro2000** [comment]
为了后续更好的体验，昨天重构了代码，备份CK，重新拉取脚本

**Comment by Mashiro2000** [comment]
> Traceback (most recent call last): File "Mashiro2000_HeyTapTask_DailyCash.py", line 22, in from HT_config import allMess,downFlag,notifyBlackList,isLottery,logger,notify ImportError: cannot import name 'allMess' from 'HT_config' (/ql/scripts/HT_config.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "Mashiro2000_HeyTapTask_DailyCash.py", line 24, in logger.info('近期代码发生重构,请前往 https://github.com/Mashiro2000/HeyTapTask 查看更新') NameError: name 'logger' is not defined

我的问题，等等

**Comment by Mashiro2000** [comment]
已更正

**Comment by requireCool** [comment]
> 已更正

可能是调试的时候忘了删，sendNotify.py里还有PushPlus的token ...

**Comment by 344108150** [comment]
谢谢啦

**Comment by Mashiro2000** [comment]
> > 已更正
> 
> 可能是调试的时候忘了删，sendNotify.py里还有PushPlus的token ...

好的，我去删除
