### ISSUE TITLE
关于定时计划

### ISSUE THREAD

**Issue by ToSeeAll** [Mashiro2000/HeyTapTask#25]
rt，大佬可以推荐一下定时列表嘛？做了个docker，只是简单的用crond一个小时执行一次，请问大佬有比较好的定时计划吗？

**Comment by Mashiro2000** [comment]
目前我是打算，全部在下去执行早上手动抽取转盘，使用脚本总数抽不到，暂时没有较好的方案

**Comment by Mashiro2000** [comment]
我后续整个定时列表

**Comment by ToSeeAll** [comment]
哦哦，好的，谢谢，star了
