### ISSUE TITLE
新版没有运行

### ISSUE THREAD

**Issue by ikam004** [Mashiro2000/HeyTapTask#26]
新版实际上没有运行成功是怎么回事呢？以下是某个日志

## 开始执行... 2021-09-30 10:43:59

鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_config`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

任务:欢太定时现金
时间:2021-09-30 10:44:02

## 执行结束... 2021-09-30 10:44:02 耗时 3 秒

**Comment by Mashiro2000** [comment]
什么平台呢

**Comment by Mashiro2000** [comment]
你CK要保存到HT——account.py

**Comment by Mashiro2000** [comment]
我的错，提示文本没改

**Comment by ikam004** [comment]
青龙面板2.9.5，已经保存到对应文件啦。好呢，等您改

**Comment by Mashiro2000** [comment]
已经完成了
