### ISSUE TITLE
腾讯云函数无法使用

### ISSUE THREAD

**Issue by wzgrx** [Mashiro2000/HeyTapTask#27]
函数创建中...

函数创建失败, 失败原因：

未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by Mashiro2000** [comment]
你的执行方法是写什么

**Comment by wzgrx** [comment]
> 你的执行方法是写什么

DailyCash.main

**Comment by Mashiro2000** [comment]
改成DailyCash.main_handler

**Comment by Mashiro2000** [comment]
其实直接复制代码到index.py就可以了
执行方法名都不用改

**Comment by wzgrx** [comment]
> 其实直接复制代码到index.py就可以了 执行方法名都不用改

好的，谢谢我试试
