### ISSUE TITLE
无法发送微信应用通知

### ISSUE THREAD

**Issue by umbrellax** [Mashiro2000/HeyTapTask#28]
大佬你好 每次执行完不会发通知。看了下 每次更新拉库，会自动重写sendnotify.py

用的拉库命令是“ql repo https://github.com/Mashiro2000/HeyTapTask.git "" "HT.*|sendNotify" "HT_config|sendNotify"

我用的是微信应用，加上之后运行任务，收不到通知不知道啥情况

我刚才手动添加了N次 “QYWX_AM = ” 这个 ==。  一是更新完库就给我重写覆盖了  二是他也不发送通知 日志里也没写

**Comment by umbrellax** [comment]
我用的是群辉docker青龙2.9.5

**Comment by Mashiro2000** [comment]
我命令更改下，更好的方案是使用青龙面板`config.sh`的·环境变量

**Comment by Mashiro2000** [comment]
你试试看，不行的话，我再去申请个微信应用，主动测试

**Comment by umbrellax** [comment]
环境变量是 “名称“ 添加一个“QYWX_AM” 
“值”再写上自己的对应的corpid,corpsecret,touser(注:多个成员ID使用|隔开),agentid
这样就行了吗 

按道理直接修改sendnotify.py这个就行了把==。

**Comment by Mashiro2000** [comment]
> 环境变量是 “名称“ 添加一个“QYWX_AM” “值”再写上自己的对应的corpid,corpsecret,touser(注:多个成员ID使用|隔开),agentid 这样就行了吗
> 
> 按道理直接修改sendnotify.py这个就行了把==。

对
