### ISSUE TITLE
有没有讨论群组

### ISSUE THREAD

**Issue by BruceSuen720** [Mashiro2000/HeyTapTask#29]
希望大佬们能建立个讨论群组呢，方便交流一下

**Comment by Mashiro2000** [comment]
没有，写这个脚本最主要是为了巩固我的学习，并没有其它意思

**Comment by Mashiro2000** [comment]
有什么问题，直接提交，看到后都会回答的

**Comment by BruceSuen720** [comment]
那个抽奖，直接用脚本挂着是抽不到的，手动进软件是可以抽到的，我觉得可能是哪里有点问题。
OPPO全家桶获取积分比这单一个欢太要高很多，一周可以四五千积分，会不会做全家桶的脚本呢，要做的话我可以帮忙提取app给你

**Comment by Mashiro2000** [comment]
> 那个抽奖，直接用脚本挂着是抽不到的，手动进软件是可以抽到的，我觉得可能是哪里有点问题。 OPPO全家桶获取积分比这单一个欢太要高很多，一周可以四五千积分，会不会做全家桶的脚本呢，要做的话我可以帮忙提取app给你

本地运行好像是没问题的，参数全部是对的，认为是因为IP的原因才导致抽不到
