### ISSUE TITLE
还是只是done但是实际上没有运行呢

### ISSUE THREAD

**Issue by ikam004** [Mashiro2000/HeyTapTask#30]
大佬，究竟是怎么回事呢。还是跟早上咨询您一样的。没有报错，就是完成，但是实际上没有运行
## 开始执行... 2021-09-30 21:46:39

鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

任务:欢太定时现金
时间:2021-09-30 21:46:43

**Comment by Mashiro2000** [comment]
我去测试下

**Comment by Mashiro2000** [comment]
我这边测试完全没问题啊，，，你把CK备份出来，按照教程步骤重新拉库
记得拉完库，修改拉库命令，确保HT_account.py不被覆盖

**Comment by ikam004** [comment]
实在太奇怪了，我下午也试过重新拉。我再试试

**Comment by ikam004** [comment]
## 开始执行... 2021-09-30 23:13:46


鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

任务:欢太定时现金
时间:2021-09-30 23:13:50

## 执行结束... 2021-09-30 23:13:51 耗时 5 秒

**Comment by ikam004** [comment]
还是一样，没报错，但是也没有运行。我直接用xshell复制文件过去覆盖HT_account.py文件的

**Comment by Mashiro2000** [comment]
我可以登录你的面板康康吗

**Comment by Mashiro2000** [comment]
除了这个脚本，其他脚本正常吗

**Comment by Mashiro2000** [comment]
你是怎么控制你的面板的，可以远程吗
