### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by JHeyzo** [Mashiro2000/HeyTapTask#31]
Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_DailyCash.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
但是依赖库里已经装了
是什么情况
![_K9NJQF%($ F 4M3_(7$6F5](https://user-images.githubusercontent.com/38498116/135491711-4a3b7aa0-720d-4d61-a867-b16a90678a60.png)

**Comment by Mashiro2000** [comment]
这应该不是我的问题啊。。。
