### ISSUE TITLE
除了任务中心外都报错了

### ISSUE THREAD

**Issue by zzfiu** [Mashiro2000/HeyTapTask#32]

**Comment by zzfiu** [comment]
鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_BattleForHeyTap.py", line 22, in <module>
    from HT_config import downFlag,notifyBlackList,isLottery,logger
ImportError: cannot import name 'isLottery' from 'HT_config' (/ql/scripts/HT_config.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Mashiro2000_HeyTapTask_BattleForHeyTap.py", line 24, in <module>
    logger.info('近期代码发生重构,请前往 https://github.com/Mashiro2000/HeyTapTask 查看更新')
NameError: name 'logger' is not defined


任务中心可以运行。


鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

任务:欢太任务中心
时间:2021-10-01 11:31:42
我	登录成功
我	今日已签到
[浏览商品]	已完成，奖励已领取
[分享商品到微信]	已完成，奖励已领取
****************************************



tg服务启动
推送成功！
企业微信服务启动
推送成功！
企业微信机器人服务启动
推送成功！

**Comment by Mashiro2000** [comment]
本地测试完，又忘记改这边的了，等等，马上修复

**Comment by Mashiro2000** [comment]
应该可以了，抱歉
