### ISSUE TITLE
QQ推送

### ISSUE THREAD

**Issue by kuake0** [Mashiro2000/HeyTapTask#33]
大佬可以大概说一下QQ推送应该怎么设置吗？我都不知道到哪里获取key

**Comment by kuake0** [comment]
用的qmsg酱，但是只有qq机器人的QQ_SKEY没有QQ_MODE

**Comment by Mashiro2000** [comment]
这个我也不清楚，我是搬运青龙里面的配置模块，至于怎么获取，我也没使用过
