### ISSUE TITLE
请问这个早睡打卡是要手动吗

### ISSUE THREAD

**Issue by lfscqk67** [Mashiro2000/HeyTapTask#34]
![Screenshot_2021-10-02-00-40-15-179_com oppo store](https://user-images.githubusercontent.com/37235589/135657124-e27d6f8b-2a1c-41ef-ad14-2b0bdc0adc5b.jpg)

**Comment by Mashiro2000** [comment]
设个定时就可以了，
比如 0 9,20 * * *
每天9点和20点执行一次

**Comment by lfscqk67** [comment]
> 设个定时就可以了， 比如 0 9,20 * * * 每天9点和20点执行一次

![image](https://user-images.githubusercontent.com/37235589/135709550-e64efc25-02a4-4ba3-a596-355f7450eea7.png)
为什么直接拉的是这样的啊
