### ISSUE TITLE
CK

### ISSUE THREAD

**Issue by kuake0** [Mashiro2000/HeyTapTask#35]
貌似不兼容 TOKENSID=TOKEN_ 开头的CK，一直登录不上，换别的欢太商城项目倒又能登录上

**Comment by Mashiro2000** [comment]
报错信息截图看看

**Comment by kuake0** [comment]
https://z3.ax1x.com/2021/10/02/4H6MLD.jpg
报错图片链接

**Comment by Mashiro2000** [comment]
这个问题很有可能是顺序不对

**Comment by Mashiro2000** [comment]
`source_type`、`TOKENSID`、`app_param`
先后顺序必须这样，否则活动做不了

**Comment by Mashiro2000** [comment]
你可以手动调换位置，我刚刚也是这样

**Comment by kuake0** [comment]
谢谢，没问题了
