### ISSUE TITLE
早睡打开推动问题

### ISSUE THREAD

**Issue by qiuyu2021** [Mashiro2000/HeyTapTask#37]
早睡打卡每次都是连续推送2条信息，额，这个正常吗

**Comment by Mashiro2000** [comment]
截图看看，

**Comment by Mashiro2000** [comment]
其它脚本会这样吗

**Comment by qiuyu2021** [comment]
> 其它脚本会这样吗

不会

**Comment by qiuyu2021** [comment]
> 截图看看，

> 

> 额 这个怎么添加图片啊 没找到

**Comment by Mashiro2000** [comment]
> > 截图看看，
> 
> > 
> 
> > 额 这个怎么添加图片啊 没找到

检查了代码，好像没问题，图片的话，直接拖到评论
![长发少女黑色吊带裙 好看的4k动漫美女壁纸3840x2160_彼岸图网](https://user-images.githubusercontent.com/40681822/135754842-0c0eb621-869a-4674-a12e-162e32b66b60.jpg)
框

**Comment by qiuyu2021** [comment]
> > > 截图看看，
> > 
> > 
> > > 
> > 
> > 
> > > 额 这个怎么添加图片啊 没找到
> 
> 检查了代码，好像没问题，图片的话，直接拖到评论框 等待上传完成即可

一直上传失败，我就手动输一下内容
第一条消息19:35:06
任务:欢太早睡打卡

时间:2021-10-03 11:35:01

我的欢太云函数 登录成功

我的欢太云函数 早睡瓜分积分，打卡成功!
第二条消息19:36:11
任务:欢太早睡打卡

时间:2021-10-03 11:35:01

我的欢太云函数 登录成功

我的欢太云函数 早睡瓜分积分，打卡成功!

我的欢太云函数 登录成功

我的欢太云函数 早睡瓜分积分,已成功打卡!

**Comment by qiuyu2021** [comment]
另外发现推送加的地址现在改了，一直报错
 url = 'http://www.pushplus.plus/send'
换成 url = 'http://pushplus.hxtrip.com/send'后可以正常推送

**Comment by Mashiro2000** [comment]
> > > > 截图看看，
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 额 这个怎么添加图片啊 没找到
> > 
> > 
> > 检查了代码，好像没问题，图片的话，直接拖到评论框 等待上传完成即可
> 
> 一直上传失败，我就手动输一下内容 第一条消息19:35:06 任务:欢太早睡打卡
> 
> 时间:2021-10-03 11:35:01
> 
> 我的欢太云函数 登录成功
> 
> 我的欢太云函数 早睡瓜分积分，打卡成功! 第二条消息19:36:11 任务:欢太早睡打卡
> 
> 时间:2021-10-03 11:35:01
> 
> 我的欢太云函数 登录成功
> 
> 我的欢太云函数 早睡瓜分积分，打卡成功!
> 
> 我的欢太云函数 登录成功
> 
> 我的欢太云函数 早睡瓜分积分,已成功打卡!

云函数会这样，emmm，去他脚本也是一样

**Comment by Mashiro2000** [comment]
> 另外发现推送加的地址现在改了，一直报错 url = 'http://www.pushplus.plus/send' 换成 url = '[http://pushplus.hxtrip.com/send'后可以正常推送](http://pushplus.hxtrip.com/send'%E5%90%8E%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E6%8E%A8%E9%80%81)

这个你可以手动替换下，我去看下pushplus，好像是没问题的，可能是你被限制发信次数了

**Comment by qiuyu2021** [comment]
> > 另外发现推送加的地址现在改了，一直报错 url = 'http://www.pushplus.plus/send' 换成 url = '[http://pushplus.hxtrip.com/send'后可以正常推送](http://pushplus.hxtrip.com/send'%E5%90%8E%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E6%8E%A8%E9%80%81)
> 
> 这个你可以手动替换下，我去看下pushplus，好像是没问题的，可能是你被限制发信次数了

刚申请的pushplus  
嗯 自己替换了
