### ISSUE TITLE
auth token is empty

### ISSUE THREAD

**Issue by awordx** [Mashiro2000/HeyTapTask#41]
## 开始执行... 2021-10-05 19:12:18

鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

任务:欢太任务中心
时间:2021-10-05 19:12:18
awordx	登录成功
awordx	失败原因:auth token is empty
****************************************

企业微信服务启动
推送成功！

## 执行结束... 2021-10-05 19:12:22 耗时 4 秒

其他任务也这样，不知道啥原因

**Comment by Mashiro2000** [comment]
登录成功，但出现`auth token is empty`是ck顺序不对，重新抓取或者手动调整顺序
