### ISSUE TITLE
积分大作战的执行频率

### ISSUE THREAD

**Issue by BlueHtml** [Mashiro2000/HeyTapTask#47]
请问2个 积分大作战 的执行频率应该设置为多少？是每天一次吗？

**Comment by BlueHtml** [comment]
积分大作战是不是失效了？运行后提示：`活动还未开始，请晚点再来`

**Comment by msccreater** [comment]
> 积分大作战是不是失效了？运行后提示：`活动还未开始，请晚点再来`

看下实际app,貌似入口没了

**Comment by Mashiro2000** [comment]
> 积分大作战是不是失效了？运行后提示：`活动还未开始，请晚点再来`

欢太的目前好像是没了，Realme还有
