### ISSUE TITLE
新增加的任务 有问题

### ISSUE THREAD

**Issue by WinverLemon** [Mashiro2000/HeyTapTask#50]
集卡赢套票

任务:集卡赢套票
时间:2021-10-14 12:46:00
Lemon 登录成功
{'code': 1100018, 'errorMessage': '该用户信息发生变化，缓存被清空'}
****************************************

欢太其它活动

任务:欢太其它活动
时间:2021-10-14 12:16:00
Lemon 登录成功
****************************************

**Comment by Mashiro2000** [comment]
> 集卡赢套票
> 
> 任务:集卡赢套票 时间:2021-10-14 12:46:00 Lemon 登录成功 {'code': 1100018, 'errorMessage': '该用户信息发生变化，缓存被清空'}
> 
> 欢太其它活动
> 
> 任务:欢太其它活动 时间:2021-10-14 12:16:00 Lemon 登录成功

我再看看吧，我这边没有这种情况

**Comment by qimaoww** [comment]
我之前也是 重新抓一下ck就好了
