### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by GOIV1999** [Mashiro2000/HeyTapTask#72]
![DV%MIQ0G7X4)_)DKK`5O{F3](https://user-images.githubusercontent.com/59191936/139377508-f69fed14-4b00-4f37-a26c-b758fb8d98a2.png)

**Comment by 11yiyang** [comment]
> > > 是云函数吗?德尼·
> > 
> > 
> > 对 云函数
> 
> 这个部署方案，不支持直接测试，只能通过触发器调用。

切换到旧版编辑器，测试事件选择【Timer 定时触发器事件模板】，修改对应参数即可直接测试。图就不贴了，切换到旧版编辑器就看到了。

**Comment by Mashiro2000** [comment]
> > > > 是云函数吗?德尼·
> > > 
> > > 
> > > 对 云函数
> > 
> > 
> > 这个部署方案，不支持直接测试，只能通过触发器调用。
> 
> 切换到旧版编辑器，测试事件选择【Timer 定时触发器事件模板】，修改对应参数即可直接测试。图就不贴了，切换到旧版编辑器就看到了。

好的，谢谢告知
