### ISSUE TITLE
之前来问为啥没推送，原来是没go-cqhttp。

### ISSUE THREAD

**Issue by 2079898548** [Mashiro2000/HeyTapTask#74]
可以考虑接入一下，我自己乱写了点，补上了。go-cqhttp确实太方便了。。我3个青龙面板都是go-cqhttp。
我主要还是想让作者弄个积分提醒，每天显示当前有多少积分，增加了多少，就和京东资产那个一样

**Comment by Mashiro2000** [comment]
> 可以考虑接入一下，我自己乱写了点，补上了。go-cqhttp确实太方便了。。我3个青龙面板都是go-cqhttp。 我主要还是想让作者弄个积分提醒，每天显示当前有多少积分，增加了多少，就和京东资产那个一样

好的哦，最近没啥动力，我找个时间写下(懒)

**Comment by Oreomeow** [comment]
贡献一个通知文件，较全
https://github.com/Oreomeow/checkinpanel/blob/master/notify_mtr_older.py

**Comment by Mashiro2000** [comment]
> 贡献一个通知文件，较全 https://github.com/Oreomeow/checkinpanel/blob/master/notify_mtr_older.py

好的

**Comment by Mashiro2000** [comment]
> 可以考虑接入一下，我自己乱写了点，补上了。go-cqhttp确实太方便了。。我3个青龙面板都是go-cqhttp。 我主要还是想让作者弄个积分提醒，每天显示当前有多少积分，增加了多少，就和京东资产那个一样

已更新，请测试下

**Comment by Mashiro2000** [comment]
指go_cqhttp

**Comment by 2079898548** [comment]
> 指go_cqhttp

推送好了，但还是在麻烦下。啥时候搞个积分查询。
