### ISSUE TITLE
积分大乱斗

### ISSUE THREAD

**Issue by kuake0** [Mashiro2000/HeyTapTask#76]
https://hd.oppo.com/act/m/2021/OnePlusJYStation/index.html?shareId=JM215776（新增的）

https://hd.oppo.com/act/m/2021/huantaishangchengjif/index.html?shareId=JM212769（原来的脚本做不完整，就做了3个）

https://hd.oppo.com/act/m/2021/2021/realmejifendalu/index.html?shareId=JM215261（没做完整也是3个）

**Comment by Mashiro2000** [comment]
好的

**Comment by Mashiro2000** [comment]
已更新
