### ISSUE TITLE
云函数推送文件有误，本地运行没问题😭

### ISSUE THREAD

**Issue by Nickyromeo** [Mashiro2000/HeyTapTask#77]
START RequestId:e9a024f5-0a65-4abe-8be7-3531c6c06578

推送文件有误

推送文件有误

失败原因:invalid syntax (sendNotify.py, line 473)

失败原因:invalid syntax (sendNotify.py, line 473)

ERROR RequestId:e9a024f5-0a65-4abe-8be7-3531c6c06578 Result:{"errorCode":-1,"errorMessage":"User process exit when running","statusCode":439}

END RequestId:e9a024f5-0a65-4abe-8be7-3531c6c06578

Report RequestId:e9a024f5-0a65-4abe-8be7-3531c6c06578 Duration:319ms Memory:128MB MemUsage:52.535156MB

**Comment by Mashiro2000** [comment]
好的，可能是云函数的python版本太低，我晚一点修正

**Comment by Oreomeow** [comment]
云函数让我头痛 hhh，海象符号报错，一堆报错

**Comment by Mashiro2000** [comment]
> 云函数让我头痛hhh，海象符号报错，一堆报错。问了开发平台，升级不了hhh

我也一样，很头疼，各种莫名其妙的错误

**Comment by wzgrx** [comment]
我也显示这种，这种是不是只有推送有问题，任务还是可以完成的？还是说都不行

**Comment by Oreomeow** [comment]
晚上测试一下看看

**Comment by Oreomeow** [comment]
## 位置形参是 Python 3.8+ 的写法，😂
```python
def excepthook(args, /):
    if issubclass(args.exc_type, requests.exceptions.RequestException):
        print(
            f"网络异常，请检查你的网络连接、推送服务器和代理配置，该错误和账号配置无关。信息：{str(args.exc_type)}, {args.thread.name}"
        )
    else:
        global default_hook
        default_hook(args)
```

**Comment by Oreomeow** [comment]
## 比较快速的解决方法是删了，这样一个推送出错直接就挂了

```python
def excepthook(args, /):
    if issubclass(args.exc_type, requests.exceptions.RequestException):
        print(
            f"网络异常，请检查你的网络连接、推送服务器和代理配置，该错误和账号配置无关。信息：{str(args.exc_type)}, {args.thread.name}"
        )
    else:
        global default_hook
        default_hook(args)


default_hook = threading.excepthook
threading.excepthook = excepthook
```

**Comment by wzgrx** [comment]
> ## 仅位置形参 `/` 是 `Python 3.8+` 的写法，😂
> * 比较快速的解决方法是删了，这样一个推送出错直接就挂了
> * [Python 文档](https://docs.python.org/3/library/threading.html)
>   ![image](https://user-images.githubusercontent.com/62660101/139661584-3c0184ff-4750-4fe4-accb-74cd292d3e95.png)
> * 删除部分
>   ```python
>   def excepthook(args, /):
>       if issubclass(args.exc_type, requests.exceptions.RequestException):
>           print(
>               f"网络异常，请检查你的网络连接、推送服务器和代理配置，该错误和账号配置无关。信息：{str(args.exc_type)}, {args.thread.name}"
>           )
>       else:
>           global default_hook
>           default_hook(args)
>   
>   
>   default_hook = threading.excepthook
>   threading.excepthook = excepthook
>   ```

START RequestId:71bbd07d-8063-41b5-b21e-11d79082e5b1
ERROR RequestId:71bbd07d-8063-41b5-b21e-11d79082e5b1 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 10, in main_handler\n    taskName = import_module(event['TriggerName'])\nKeyError: 'TriggerName'","statusCode":430}
END RequestId:71bbd07d-8063-41b5-b21e-11d79082e5b1
Report RequestId:71bbd07d-8063-41b5-b21e-11d79082e5b1 Duration:1ms Memory:128MB MemUsage:8.023438MB
删了还是失败。。

**Comment by Oreomeow** [comment]
@wzgrx 你的测试方法不对

`切换到旧版编辑器` -> 测试事件选择 `Timer 定时触发器事件模版` -> 举例： `"TriggerName":"TaskCenter"`

**Comment by wzgrx** [comment]
> @wzgrx 你的测试方法不对
> 
> `切换到旧版编辑器` -> 测试事件选择 `Timer 定时触发器事件模版` -> 举例： `"TriggerName":"TaskCenter"`

START RequestId:6e841864-82af-4830-a914-e79f82752bbe

缺少json5依赖！程序将尝试安装依赖！

ERROR RequestId:6e841864-82af-4830-a914-e79f82752bbe Result:{"errorCode":-1,"errorMessage":"User process exit when running","statusCode":439}

END RequestId:6e841864-82af-4830-a914-e79f82752bbe

Report RequestId:6e841864-82af-4830-a914-e79f82752bbe Duration:317ms Memory:128MB MemUsage:17.015625MB

**Comment by Oreomeow** [comment]
@wzgrx 我提了 PR，你用这个测试

- [sendNotify.py](https://raw.githubusercontent.com/Oreomeow/HeyTapTask/main/sendNotify.py)

**Comment by Oreomeow** [comment]
云函数的依赖包要附在 `src` 文件夹里面，安装似乎不行

**Comment by wzgrx** [comment]
> @wzgrx 我提了 PR，你用这个测试
> 
> * [sendNotify.py](https://raw.githubusercontent.com/Oreomeow/HeyTapTask/main/sendNotify.py)

还是不行。。
START RequestId:04d5f31e-d171-4487-9d23-d3a2144bdcad

推送文件有误

推送文件有误

失败原因:invalid syntax (sendNotify.py, line 466)

失败原因:invalid syntax (sendNotify.py, line 466)

ERROR RequestId:04d5f31e-d171-4487-9d23-d3a2144bdcad Result:{"errorCode":-1,"errorMessage":"User process exit when running","statusCode":439}

END RequestId:04d5f31e-d171-4487-9d23-d3a2144bdcad

Report RequestId:04d5f31e-d171-4487-9d23-d3a2144bdcad Duration:306ms Memory:128MB MemUsage:16.500000MB

**Comment by Oreomeow** [comment]
@wzgrx 忘记删了那段......

**Comment by Oreomeow** [comment]
@wzgrx 这次应该可以了......

**Comment by wzgrx** [comment]
> @wzgrx 忘记删了那段，这次应该可以了......

可以了，可以了，感谢开发者打佬，辛苦了

**Comment by Oreomeow** [comment]
> > @wzgrx 忘记删了那段，这次应该可以了......
> 
> 可以了，可以了，感谢开发者打佬，辛苦了

你测试的是哪种配信方式，有可能的话多测试几种看看

**Comment by Nickyromeo** [comment]
> > > @wzgrx忘记拥有了那段，大家应该可以了......
> > 
> > 
> > 可以了，可以了，感谢开发者打佬，辛苦了
> 
> 你是测试吸尘器配信方式，有可能的话多测几种

感谢大佬，测试push+和企业微信应用都没问题了

**Comment by Mashiro2000** [comment]
> ## 仅位置形参 `/` 是 `Python 3.8+` 的写法，😂
> * 已提 PR：[移除 `sendNotify.py` 异常捕获代码和第三方库 `json5` #80](https://github.com/Mashiro2000/HeyTapTask/pull/80)
> * 比较快速的解决方法是删了，这样一个推送出错直接就挂了
> * [Python 文档](https://docs.python.org/3/library/threading.html)
>   ![image](https://user-images.githubusercontent.com/62660101/139661584-3c0184ff-4750-4fe4-accb-74cd292d3e95.png)
> * 删除部分
>   ```python
>   def excepthook(args, /):
>       if issubclass(args.exc_type, requests.exceptions.RequestException):
>           print(
>               f"网络异常，请检查你的网络连接、推送服务器和代理配置，该错误和账号配置无关。信息：{str(args.exc_type)}, {args.thread.name}"
>           )
>       else:
>           global default_hook
>           default_hook(args)
>   
>   
>   default_hook = threading.excepthook
>   threading.excepthook = excepthook
>   ```
> 
> ## 测试方法
> `切换到旧版编辑器` -> 测试事件选择 `Timer 定时触发器事件模版` -> 举例： `"TriggerName":"TaskCenter"`

python的asyncio也难以兼容云函数
，很多语法是3.7才出现的，结果3.10就移除了，emm

**Comment by changyexing** [comment]
> @wzgrx 忘记删了那段，这次应该可以了......

![image](https://user-images.githubusercontent.com/47708150/139801695-d7579efc-f4dd-4ff0-be30-121b36b8f848.png)
老哥，我只删除了sendnotify里那两段代码，还是这样。我还需要修改其他地方吗？

**Comment by Oreomeow** [comment]
@changyexing `triggername` 改了吗，没有 `everyday` 这个模块或者脚本

**Comment by changyexing** [comment]
> @changyexing `triggername` 改了吗，没有 `Everyday` 这个模块或者脚本

![image](https://user-images.githubusercontent.com/47708150/139820991-1bee2cba-3b1d-4995-80eb-aa33f8ba8fdd.png)
这是改了之后的，还是有问题

**Comment by changyexing** [comment]
> @changyexing `triggername` 改了吗，没有 `Everyday` 这个模块或者脚本

![image](https://user-images.githubusercontent.com/47708150/139821318-983f1288-048a-44a9-a6b5-822463d991ba.png)
我看了上面你说的解决办法，但我不是很懂要怎么操作，您能说详细点吗？

**Comment by Oreomeow** [comment]
@changyexing 直接更新到当前仓库最新文件即可，然后按测试方法操作

**Comment by changyexing** [comment]
> @changyexing 直接更新到当前仓库最新文件即可，然后按测试方法操作

我就是今天刚下的文件啊。。。刚接触这个

**Comment by changyexing** [comment]
> @changyexing 直接更新到当前仓库最新文件即可，然后按测试方法操作

![image](https://user-images.githubusercontent.com/47708150/139853120-45dfd4ab-1172-4f22-8d5c-37e1458945ec.png)

well搞定了，但是我测试的时候每次还要改划圈的名字，这个有影响吗？我不用管他吗？

**Comment by Oreomeow** [comment]
@changyexing 测试是测试，实际运行是运行，你看你能不能收到通知不就行了

**Comment by changyexing** [comment]
> @changyexing 测试是测试，实际运行是运行，你看你能不能收到通知不就行了

好吧好吧，明天见分晓~多谢老哥啦~

**Comment by XiaChuerwu** [comment]
START RequestId:88f412d7-68e5-44b6-8307-818d6db2062c

ERROR RequestId:88f412d7-68e5-44b6-8307-818d6db2062c Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 10, in main_handler\n    taskName = import_module(event['TriggerName'])\nKeyError: 'TriggerName'","statusCode":430}

END RequestId:88f412d7-68e5-44b6-8307-818d6db2062c

问一下大哥们这是什么错误

**Comment by wzgrx** [comment]
作者能不能把这个issue关闭了，谢谢，想问问题可以另外提issue，不要在这里回复了
