### ISSUE TITLE
用户未登录

### ISSUE THREAD

**Issue by z2135** [Mashiro2000/HeyTapTask#82]
![Screenshot_2021-11-03-07-52-22-776_com tencent mm](https://user-images.githubusercontent.com/78579037/139967302-1b76c269-bfaa-45dd-b01a-3fec56657fc5.png)
用了最新的文件，显示用户未登录，但有的任务却又成功了，换了好几次ck依旧如此

**Comment by Mashiro2000** [comment]
你可以把获取到的CK发我，我这边测试下，不用做任何处理
CK和UA信息需自行抓包，欢太商城 -> 我的 -> 任务中心 -> 领券中心

抓包地址:https://store.oppo.com/cn/oapi/users/web/checkPeople/isNewPeople

**Comment by Mashiro2000** [comment]
463022229@qq.com
