### ISSUE TITLE
求助push plus无法推送

### ISSUE THREAD

**Issue by changyexing** [Mashiro2000/HeyTapTask#84]
![image](https://user-images.githubusercontent.com/47708150/140052990-7337d738-c512-4491-aec9-d33308ca4fc6.png)

![image](https://user-images.githubusercontent.com/47708150/140053027-2334844b-ec3d-4bc5-a450-24051eb4b210.png)

![image](https://user-images.githubusercontent.com/47708150/140052936-6c82e7be-d17c-44cb-84c5-d9fa722dc47c.png)
sever酱是可以正常推送的，但它只有五个免费名额不够用，就想换到push+，但出现了上图错误，求助老哥看下是哪里问题？

**Comment by Oreomeow** [comment]
- 已测试，不存在问题
- 可能原因：填了不是必填项的群组编码后，没有扫码加入该推送群组

**Comment by changyexing** [comment]
> * 已测试，不存在问题
> * 可能原因：填了不是必填项的群组编码后，没有扫码加入该推送群组

扫过了，微信添加了的，我收到提示了...

**Comment by Oreomeow** [comment]
@changyexing 尝试删除群组编码 `001` 直接进行推送来排除网络问题

**Comment by Oreomeow** [comment]
还有个可能是 pushplus 网址有两个，推送脚本使用的是新的 `pushplus.plus`

**Comment by changyexing** [comment]
> @changyexing 尝试删除群组编码 `001` 直接进行推送来排除网络问题

我就是先只用了token，没反应才创建了个群组😂

**Comment by changyexing** [comment]
> 还有个可能是 pushplus 网址有两个，推送脚本使用的是新的 `pushplus.plus`
我人麻了，pushplus怎么会有两个网站，公众号还是各自独立的
一个是http://pushplus.hxtrip.com/
另一个是http://www.pushplus.plus/
换了第二个一个没问题了。。。。。

**Comment by changyexing** [comment]
> 还有个可能是 pushplus 网址有两个，推送脚本使用的是新的 `pushplus.plus`


我人麻了，pushplus怎么会有两个网站，公众号还是各自独立的
一个是http://pushplus.hxtrip.com/
另一个是http://www.pushplus.plus/
换了第二个一个没问题了。。。。。

**Comment by Oreomeow** [comment]
- [notify_mtr_json.py](https://github.com/Oreomeow/checkinpanel/blob/master/notify_mtr_json.py)

我仓库的通知文件已兼容两个网址
