### ISSUE TITLE
配置完成，运行后啥都不显示

### ISSUE THREAD

**Issue by cisco6005** [Mashiro2000/HeyTapTask#89]
## 开始执行... 2021-11-06 20:05:55

鉴于青龙面板会破坏欢太CK格式，尝试修复无效，故建议使用配置文件
该项目不再支持青龙面板`环境变量`添加账号,请将CK转移至配置文件
青龙面板 -> 脚本管理 -> 搜索`HT_account`关键字 -> 编辑
CK最简格式:'source_type=xxx;TOKENSID=xxx;app_param=xxx;'

任务:RealMe积分大乱斗
时间:2021-11-06 20:05:58
企业微信机器人服务启动
企业微信机器人推送成功！

## 执行结束... 2021-11-06 20:05:59 耗时 4 秒

=========================
所有脚本都是这个提示，CK已经抓取，UA也抓取了

**Comment by cisco6005** [comment]
看到APP啥都没执行

**Comment by Mashiro2000** [comment]
解决了吗，我这边没有问题啊

**Comment by Oreomeow** [comment]
#90

**Comment by cisco6005** [comment]
还是那样，我新建了容器，重新部署了，也是这样，难道我脸黑？
