### ISSUE TITLE
auth token is empty,重新抓包也不行

### ISSUE THREAD

**Issue by KeyueMiao** [Mashiro2000/HeyTapTask#90]
如题,并且大概与IP无关,因为在本地端和云函数端测试都是这样.
已经重抓多次ck,均无法解决

**Comment by KeyueMiao** [comment]
**看了下代码,又看了下错误日志**

- 登陆是正常的,错误出现在执行任务之时
- 执行任务时提示auth token is empty,说明执行任务需要传送token这一参数
- 而作者貌似在进行完会话的建立之后,之后的任务都只是重用此会话,而没有传送token(cookie)
- 可以考虑重用会话时加上cookie试试(毕竟token在cookie段里)

代码能力羸弱,就是提个可能的问题解决思路

**Comment by JackA1ltman** [comment]
抓包最好利用httpcanary抓包，在领券中心抓包，会找到token，格式应该是TOKEN_*****这样，同时也有source_type，但没找到app_param

**Comment by KeyueMiao** [comment]
> 抓包最好利用httpcanary抓包，在领券中心抓包，会找到token，格式应该是TOKEN_*****这样，同时也有source_type，但没找到app_param

我和你的抓包流程是一样的,含有token字段.
不过在这个source_type上,我出问题的这个账号无论重抓多少次也没有出现,另一个正常账号每次抓都能出现

**Comment by KeyueMiao** [comment]
> 抓包最好利用httpcanary抓包，在领券中心抓包，会找到token，格式应该是TOKEN_*****这样，同时也有source_type，但没找到app_param

我和你的抓包流程是一样的,含有token字段,也含有source_type,app_param也有 ,这就离谱

**Comment by JackA1ltman** [comment]
我没有app_param，你的是什么版本的欢太啊

**Comment by KeyueMiao** [comment]
> 我没有app_param，你的是什么版本的欢太啊

最新版的,改名叫OPPO商城的那个

**Comment by KeyueMiao** [comment]
**测试表明欢太所需CK为: source_type、TOKENSID、app_param,顺序不可乱**

我找到问题了,我这个问题账号抓出来的ck 的这三个参数是乱的,此贴终结
