### ISSUE TITLE
sendNotify.py冲突

### ISSUE THREAD

**Issue by a54731037** [Mashiro2000/HeyTapTask#91]
我青龙面板装了京东脚本，所以用的是他的推送。
但是昨天发现继续用那个会导致欢太脚本跑不起来提示 invalid syntax
现在我把sendNotify.py换成你的了，又无法收到原本京东青龙的推送

**Comment by Oreomeow** [comment]
请提供必要的截图

**Comment by fxxcl** [comment]
> 请提供必要的截图，青龙的推送 py 脚本和这个是同一个

![Screenshot_20211108-004946](https://user-images.githubusercontent.com/71049084/140654187-5fda010b-1977-4f29-9bc7-4b494d85c0fd.jpg)

**Comment by Oreomeow** [comment]
好的，问题在于青龙 python 的安装位置和 Linux 系统不一致

**Comment by Oreomeow** [comment]
@fxxcl 提供下 `sendNotify.py` 文件的截图

**Comment by FuxkTME** [comment]
> > 请提供必要的截图，青龙的推送 py 脚本和这个是同一个
> 
> ![Screenshot_20211108-004946](https://user-images.githubusercontent.com/71049084/140654187-5fda010b-1977-4f29-9bc7-4b494d85c0fd.jpg)

我也出现了这个，晚上的早睡打卡也无了T^T

**Comment by Oreomeow** [comment]
> > > 请提供必要的截图，青龙的推送 py 脚本和这个是同一个
> > 
> > 
> > ![Screenshot_20211108-004946](https://user-images.githubusercontent.com/71049084/140654187-5fda010b-1977-4f29-9bc7-4b494d85c0fd.jpg)
> 
> 我也出现了这个，晚上的早睡打卡也无了T^T

测试中未出现图中情况

**Comment by Oreomeow** [comment]
有一种可能是 ghproxy 代理失败，拉取的通知文件未正确下载

**Comment by Oreomeow** [comment]
例如通知文件空白或下载的内容实为 html

**Comment by FuxkTME** [comment]
![image](https://user-images.githubusercontent.com/45877136/140656632-983cd6e2-a190-4066-be69-45a83f3e040c.png)
![image](https://user-images.githubusercontent.com/45877136/140656649-ae00e438-c42e-4af2-b477-a47bd5eb3f72.png)

**Comment by Oreomeow** [comment]
@FuxkTME 重新运行拉库命令

**Comment by FuxkTME** [comment]
> @FuxkTME 重新运行拉库命令

提示Auto-merge失败，我把原repo里面的库删了，重新拉就好了， 谢谢大佬

**Comment by lzl8800** [comment]
> > @FuxkTME 重新运行拉库命令
> 
> 提示Auto-merge sendnotify.py失败，我把原repo里面的库删了，重新拉就好了， 谢谢大佬

是把sendnotify.py文件删了重新拉库吗，我也提示Auto-merge sendnotify.py了

**Comment by FuxkTME** [comment]
> > > @FuxkTME 重新运行拉库命令
> > 
> > 
> > 提示Auto-merge sendnotify.py失败，我把原repo里面的库删了，重新拉就好了， 谢谢大佬
> 
> 是把sendnotify.py文件删了重新拉库吗，我也提示Auto-merge sendnotify.py了
/ql/repo/Ma........，这一整个文件夹

**Comment by lzl8800** [comment]
> > > > @FuxkTME 重新运行拉库命令
> > > 
> > > 
> > > 提示Auto-merge sendnotify.py失败，我把原repo里面的库删了，重新拉就好了， 谢谢大佬
> > 
> > 
> > 是把sendnotify.py文件删了重新拉库吗，我也提示Auto-merge sendnotify.py了
> > /ql/repo/Ma........，这一整个文件夹

解决了，谢谢老哥

**Comment by fxxcl** [comment]
删了以后好一阵，sendnotify变html文件的问题继续出现，没找到解决根源
