### ISSUE TITLE
用的腾讯云函数，其他任务都能执行成功，只有这个TaskCenter.py会执行失败，大佬帮忙看看是什么问题，谢谢

### ISSUE THREAD

**Issue by mting1117** [Mashiro2000/HeyTapTask#93]
以下是日志：
START RequestId:5e8dfe92-b68e-462d-b75f-0789a36e0cb5
ERROR RequestId:5e8dfe92-b68e-462d-b75f-0789a36e0cb5 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 10, in main_handler\n    taskName = import_module(event['TriggerName'])\n  File \"/var/lang/python3/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 978, in _gcd_import\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 961, in _find_and_load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 948, in _find_and_load_unlocked\nModuleNotFoundError: No module named 'Taskcenter'","statusCode":430}
END RequestId:5e8dfe92-b68e-462d-b75f-0789a36e0cb5
Report RequestId:5e8dfe92-b68e-462d-b75f-0789a36e0cb5 Duration:1ms Memory:128MB MemUsage:8.054688MB

**Comment by Oreomeow** [comment]
```shell
ModuleNotFoundError: No module named 'Taskcenter'
```
检查一下哪里的这个没有大写
应为 `TaskCenter`

**Comment by mting1117** [comment]
谢谢大佬，应该是我自动触发的任务名称没有大写
