### ISSUE TITLE
欢太每日现金有问题

### ISSUE THREAD

**Issue by jwdstef** [Mashiro2000/HeyTapTask#94]
![huantaio](https://user-images.githubusercontent.com/3320789/140671280-0a81106d-a4ec-4f52-9299-ef43b3e811c2.png)
其实五个号都已经领过初始红包了，但是有一个可以做任务，其他四个都是说未领初始红包

**Comment by Mashiro2000** [comment]
明天再看看，这几天没啥时间

**Comment by benzBrake** [comment]
> 
> 
> 明天再看看，这几天没啥时间

还有个请求，能不能把每日现金互相邀请功能加上，我一般都是挂3个号

**Comment by Mashiro2000** [comment]
后续考虑
