### ISSUE TITLE
可否加一个 统计前一天收益以及积分总余额的统计

### ISSUE THREAD

**Issue by 344108150** [Mashiro2000/HeyTapTask#95]
大神，不知道是否可行，因为好几个号

**Comment by Mashiro2000** [comment]
有计划，但被其它项目搁着了，明天后就有时间了

**Comment by 344108150** [comment]
谢谢啦

**Comment by Mashiro2000** [comment]
> 谢谢啦

找不到获取昨日积分数据的api，只找到显示积分总数，后续再看看
还有一个方案，可以使用文件存储，但我感觉不太好

**Comment by benzBrake** [comment]
> 
> 
> > 谢谢啦
> 
> 找不到获取昨日积分数据的api，只找到显示积分总数，后续再看看 还有一个方案，可以使用文件存储，但我感觉不太好

目前可以使用积分明细接口统计，但是感觉不优雅。
我记得老版本APP有最近一周的带数值折线图，不知道API还在不在。

**Comment by 344108150** [comment]
有一个按月份查询积分的接口，结果出来了之后把数据整理一下 找出昨天的  应该可行
