### ISSUE TITLE
RealMe积分大乱斗

### ISSUE THREAD

**Issue by cuncun-edg** [Mashiro2000/HeyTapTask#97]
运行成功但是没有出现日志
![image](https://user-images.githubusercontent.com/77426305/140692390-2029502c-76b7-4814-8e02-5a49adea7335.png)

**Comment by Oreomeow** [comment]
检查 CK，检查拉库命令，重新运行拉库命令

**Comment by cuncun-edg** [comment]
> 检查CK，检查拉库命令，运行拉库命令

![image](https://user-images.githubusercontent.com/77426305/140697183-c70e5dec-d454-455b-ac6e-e1416e15ee71.png)
填写ck之后 其他任务可运行有日志，只要RealMe积分大乱斗 加油任务 无日志，ck是保存的 可是之后检查 又是显示没有填写ck

**Comment by Oreomeow** [comment]
@cuncun-edg README 认真看了吗，拉库命令是否更改过？

**Comment by cuncun-edg** [comment]
> @cuncun-g README 是否真的看到了，拉库命令？

重新填写ck就可以运行，并没有重新拉库，感谢指导，我遇到的问题就是 明明填写了ck过段时间到配置文件里查看ck值为空

**Comment by Mashiro2000** [comment]
> 检查 CK，检查拉库命令，重新运行拉库命令

谢谢老哥，一直帮我回答问题
