### ISSUE TITLE
🔈 Git 冲突，容器内运行 `rm -rf /ql/scripts/ Mashiro2000_HeyTapTask_* && rm -rf /ql/repo/Mashiro2000_HeyTapTask` 清空文件后重新拉库即可

### ISSUE THREAD

**Issue by pyf60** [Mashiro2000/HeyTapTask#98]
![image](https://user-images.githubusercontent.com/38612309/140698801-11bd5ca6-e02a-4acc-a705-4c6a90a86ae6.png)

**Comment by Oreomeow** [comment]
运行拉库命令更新即可，不行就删除文件再拉

**Comment by pyf60** [comment]
依旧是这个错误。

**Comment by Oreomeow** [comment]
@pyf60 截取 sendNotify.py 102 行附近

**Comment by pyf60** [comment]
![image](https://user-images.githubusercontent.com/38612309/140700815-1502a112-095e-41df-83db-74f21388cb49.png)

**Comment by runishiwo** [comment]
rm -rf /ql/scripts/ Mashiro2000_HeyTapTask_*
rm -rf /ql/repo/Mashiro2000_HeyTapTask

把这两个地方删了，重新拉一下库就好了，我就是这样
不过ck要重新抓一下

**Comment by Oreomeow** [comment]
@pyf60 git 冲突，删除所有相关脚本

**Comment by pyf60** [comment]
好的

**Comment by 7L787** [comment]
删除了文件也重新拉库了但是还是不行

**Comment by 7L787** [comment]
![图片](https://user-images.githubusercontent.com/87010245/140917652-4e840cd9-b248-41a9-8642-e9bf017e668f.png)

**Comment by 7L787** [comment]
我把提示错误的文件删除了，然后重新下载就好了

**Comment by whyman365** [comment]
> 我把提示错误的文件删除了，然后重新下载就好了

删了重拉确实好了，但是第二天问题依旧。每天删一次运行也不是办法

**Comment by 56warmers** [comment]
> > 我把提示错误的文件删除了，然后重新下载就好了
> 
> 删了重拉确实好了，但是第二天问题依旧。每天删一次运行也不是办法

你是青龙吗？如果是青龙可以选择不再每天拉库更新，然后去修改对应的sendNotify.py文件报错的行，开头一般多一个缩进的，python对缩进敏感

**Comment by Oreomeow** [comment]
@56warmers 不是缩进问题，是那天 git reset 了然后代码冲突了

**Comment by Oreomeow** [comment]
@56warmers 不是缩进问题，是那天 git reset 了然后代码冲突了

**Comment by 56warmers** [comment]
> @56warmers 不是缩进问题，是那天 git reset 了然后代码冲突了

好的，感谢配信作者大大

**Comment by 7L787** [comment]
那现在这个问题有解决办法吗各位大佬

**Comment by pyf60** [comment]
解决了
