### ISSUE TITLE
推送文件有误 失败原因:expected an indented block (sendNotify.py, line 102)

### ISSUE THREAD

**Issue by nenene908** [Mashiro2000/HeyTapTask#99]
![image](https://user-images.githubusercontent.com/74109802/140768481-2564e060-aa53-4088-9b25-5d24ca7d5c25.png)

**Comment by leiletter** [comment]
也是这个问题，给我搞烦了，按照readme的拉库命令，日志如下，接下来运行就是sendNotify错误。我自己下载了个，覆盖进去，把sendnotify加黑名单就好了
开始更新仓库：/ql/repo/Mashiro2000_HeyTapTask

Fetching origin
HEAD is now at c7a8a67 [DEV] 测试通知文件异常捕获
Auto-merging sendNotify.py
CONFLICT (content): Merge conflict in sendNotify.py
Automatic merge failed; fix conflicts and then commit the result.

更新/ql/repo/Mashiro2000_HeyTapTask成功...

**Comment by Oreomeow** [comment]
#98
